<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(StandardTargetFrameworkIds)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LiteDB" Version="5.0.17" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FEx.Utilities\FEx.Utilities.csproj" />
  </ItemGroup>

</Project>
