<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(WindowsTargetFrameworkIds)</TargetFrameworks>
		<UseWPF>true</UseWPF>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
		<UseWindowsForms>true</UseWindowsForms>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\FEx.WPFx\FEx.WPFx.csproj" />
	</ItemGroup>

</Project>
