<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(StandardTargetFrameworkIds)</TargetFrameworks>
		<Description>Interfaces and abstractions for modular DI registration, service providers, and configurators</Description>
		<Configurations>Debug;Release;Build</Configurations>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="$(DotNetNugetsVersion)" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="$(DotNetNugetsVersion)" />
		<PackageReference Include="StrongInject.Extensions.DependencyInjection" Version="1.4.4" />
		<PackageReference Include="System.Collections.Immutable" Version="$(DotNetNugetsVersion)" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Agnostics.Abstractions\FEx.Agnostics.Abstractions.csproj" />
	</ItemGroup>

</Project>
