<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>$(TargetFrameworkId)</TargetFramework>
	  <UserSecretsId>a02b56ea-923b-45ca-9153-95c5b63981e4</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Graph" Version="4.24.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FEx.Extensions\FEx.Extensions.csproj" />
  </ItemGroup>

</Project>
