<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>$(StandardTargetFrameworkIds)</TargetFrameworks>
		<Description>Legacy utilities for async task handling, secure file wipe, MVVM progress tracking, and imaging</Description>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="System.Management" Version="$(DotNetNugetsVersion)" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\FEx.MVVM\FEx.MVVM.csproj" />
		<ProjectReference Include="..\FEx.MVVM.Rx.Legacy\FEx.MVVM.Rx.Legacy.csproj" />
		<ProjectReference Include="..\FEx.Webx\FEx.Webx.csproj" />
	</ItemGroup>
</Project>
