<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>$(StandardTargetFrameworkIds)</TargetFrameworks>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="System.Management" Version="8.0.0" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\FEx.Abstractions\FEx.Abstractions.csproj" />
		<ProjectReference Include="..\FEx.Basics\FEx.Basics.csproj" />
		<ProjectReference Include="..\FEx.Extensions\FEx.Extensions.csproj" />
		<ProjectReference Include="..\FEx.MVVM\FEx.MVVM.csproj" />
	</ItemGroup>
</Project>
