<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>$(StandardTargetFrameworkIds)</TargetFrameworks>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="System.Management" Version="$(DotNetNugetsVersion)" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\FEx.MVVM\FEx.MVVM.csproj" />
		<ProjectReference Include="..\FEx.Webx\FEx.Webx.csproj" />
	</ItemGroup>
</Project>
