<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(FullTargetFrameworkId)</TargetFramework>
		<UseWPF>true</UseWPF>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\AzureDevOpsx\FEx.AzureDevOpsx.csproj" />
	</ItemGroup>

</Project>
