<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(WindowsTargetFrameworkIds)</TargetFrameworks>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\MSBuildx\FEx.MSBuildx.csproj" />
	</ItemGroup>

</Project>
