<Project>

	<Import Project="$(MSBuildThisFileDirectory)\DevConfigs\Directory.Build.props" />

	<PropertyGroup Condition=" '$(IsPackable)' == 'True' ">
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<PackageIcon>flakroup.png</PackageIcon>
		<WarnOnPackingNonPackableProject>true</WarnOnPackingNonPackableProject>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://gitlab.com/flakroup/FEx</PackageProjectUrl>
		<RepositoryUrl>https://gitlab.com/flakroup/FEx.git</RepositoryUrl>
	</PropertyGroup>

	<ItemGroup Condition=" '$(IsPackable)' == 'True' ">
		<None Include="$(MSBuildThisFileDirectory)\flakroup.png">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
	</ItemGroup>

</Project>