<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFrameworkId)</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\FEx.Extensions\FEx.Extensions.csproj" />
	</ItemGroup>

</Project>
