<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(TargetFrameworkIds)</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="System.Reactive.Linq" Version="6.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\FEx.Utilities\FEx.Utilities.csproj" />
	</ItemGroup>

</Project>
