<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(TargetFrameworkIds)</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="DynamicData" Version="7.14.2" />
		<PackageReference Include="ReactiveUI" Version="18.4.44" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FEx.Abstractions\FEx.Abstractions.csproj" />
		<ProjectReference Include="..\FEx.Fundamentals\FEx.Fundamentals.csproj" />
		<ProjectReference Include="..\FEx.MVVM.Abstractions\FEx.MVVM.Abstractions.csproj" />
	</ItemGroup>

</Project>