<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFrameworkId)</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ReactiveUI" Version="18.4.26" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FEx.Fundamentals\FEx.Fundamentals.csproj" />
		<ProjectReference Include="..\FEx.MVVM.Abstractions\FEx.MVVM.Abstractions.csproj" />
	</ItemGroup>

</Project>