<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFrameworkId)</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="StrongInject.Extensions.DependencyInjection" Version="1.4.4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FEx.Utilities\FEx.Utilities.csproj" />
	</ItemGroup>

</Project>
