<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(StandardTargetFrameworkIds)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="StrongInject.Extensions.DependencyInjection" Version="1.4.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FEx.Fundamentals\FEx.Fundamentals.csproj" />
  </ItemGroup>

</Project>
