// <auto-generated />

using FEx.Imaging.Windows.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace FEx.Imaging.Windows.Migrations
{
    [DbContext(typeof(FilesCacheContext))]
    [Migration("20200610104919_Add_Size_Columns")]
    partial class Add_Size_Columns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("FEx.Imaging.Windows.Model.IndexEntry", b =>
                {
                    b.Property<string>("AbsoluteUri")
                        .HasMaxLength(1024);

                    b.Property<string>("CheckSum")
                        .HasMaxLength(1024);

                    b.Property<string>("FilePath")
                        .HasMaxLength(1024);

                    b.Property<int>("PixelHeight");

                    b.Property<int>("PixelWidth");

                    b.Property<long>("ResponseContentLength");

                    b.HasKey("AbsoluteUri");

                    b.HasIndex("FilePath");

                    b.ToTable("IndexEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
