<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(StandardTargetFrameworkIds)</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="StrongInject" Version="1.4.4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FEx.Basics\FEx.Basics.csproj" />
		<ProjectReference Include="..\FEx.DependencyInjection.Abstractions\FEx.DependencyInjection.Abstractions.csproj" />
		<ProjectReference Include="..\FEx.Extensions\FEx.Extensions.csproj" />
		<ProjectReference Include="..\FEx.Json\FEx.Json.csproj" />
	</ItemGroup>

</Project>
