<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetWindowsFrameworkId)</TargetFramework>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="WpfBindingErrors" Version="1.1.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FEx.DependencyInjection\FEx.DependencyInjection.csproj" />
	</ItemGroup>

</Project>
