<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(TargetFrameworkIds)</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Flurl.Http" Version="4.0.0-pre4" />
		<PackageReference Include="Polly" Version="8.2.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FEx.Extensions\FEx.Extensions.csproj" />
	</ItemGroup>

</Project>
