<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFrameworkId)</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Flurl.Http" Version="3.2.4" />
		<PackageReference Include="Polly" Version="7.2.3" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
	</ItemGroup>

</Project>
