[project]
name = "FEx.Agnostics"
path = "rc\\Agnostics"

[[classes]]
name = "NotifyPropertyChanged"
ns = "FEx.Agnostics.BaseObjects"
base = "PropertyChangeAware, IFExNotifyPropertyChanged"
file = "BaseObjects\\NotifyPropertyChanged.cs"

[[classes]]
name = "PropertyChangeAware"
ns = "FEx.Agnostics.BaseObjects"
file = "BaseObjects\\PropertyChangeAware.cs"

[[classes]]
name = "PaginatedList"
ns = "FEx.Agnostics.Collections"
file = "Collections\\PaginatedList.cs"

[[classes]]
name = "SummarizedPaginatedList"
ns = "FEx.Agnostics.Collections"
base = "PaginatedList<T>"
file = "Collections\\SummarizedPaginatedList.cs"

[[classes]]
name = "CollectionDebugView"
ns = "FEx.Agnostics.Collections.Concurrent"
file = "Collections\\Concurrent\\CollectionDebugView.cs"

[[classes]]
name = "ConcurrentList"
ns = "FEx.Agnostics.Collections.Concurrent"
base = "BaseConcurrentList<T>, IConcurrentList<T>"
file = "Collections\\Concurrent\\ConcurrentList.cs"

[[classes]]
name = "ConcurrentList"
ns = "FEx.Agnostics.Collections.Concurrent"
file = "Collections\\Concurrent\\ConcurrentList.Impl.cs"

[[classes]]
name = "ConcurrentSortableList"
ns = "FEx.Agnostics.Collections.Concurrent"
base = "ConcurrentList<T> where T : IComparable<T>"
file = "Collections\\Concurrent\\ConcurrentSortableList.cs"

[[classes]]
name = "FExMemoryCache"
ns = "FEx.Agnostics.Collections.Concurrent"
base = "IFExMemoryCache<TKey, TValue>, IDictionary<TKey, TValue>, IDictionary"
file = "Collections\\Concurrent\\FExMemoryCache.cs"

[[classes]]
name = "ListDebugView"
ns = "FEx.Agnostics.Collections.Concurrent"
file = "Collections\\Concurrent\\ListDebugView.cs"

[[classes]]
name = "AlphanumComparatorFast"
ns = "FEx.Agnostics.Comparers"
base = "IComparer<string>, IEqualityComparer<string>"
file = "Comparers\\AlphanumComparatorFast.cs"

[[classes]]
name = "NonSpaceIgnoringStringComparer"
ns = "FEx.Agnostics.Comparers"
base = "IEqualityComparer<string>"
file = "Comparers\\NonSpaceIgnoringStringComparer.cs"

[[classes]]
name = "FExException"
ns = "FEx.Agnostics.Exceptions"
base = "Exception"
file = "Exceptions\\FExException.cs"

[[classes]]
name = "AsyncReaderWriterLockSlimExtension"
ns = "FEx.Agnostics.Extensions"
summary = "Contains extension methods for ."
file = "Extensions\\AsyncReaderWriterLockSlimExtension.cs"
static = true

[[interfaces]]
name = "IDisposableLock"
ns = "FEx.Agnostics.Extensions"
summary = "Downgrades the lock from write mode to read mode."
file = "Extensions\\AsyncReaderWriterLockSlimExtension.cs"

[[extensions]]
name = "GetReadLock"
sig = "IDisposableLock GetReadLock(this AsyncReaderWriterLockSlim lockInstance,
                                              CancellationToken cancellationToken = default)"
returns = "IDisposableLock"
summary = "Enters the lock in read mode."
file = "Extensions\\AsyncReaderWriterLockSlimExtension.cs"

[[extensions]]
name = "TryGetReadLock"
sig = "IDisposableLock TryGetReadLock(this AsyncReaderWriterLockSlim lockInstance,
                                                 int millisecondsTimeout,
                                                 CancellationToken cancellationToken = default)"
returns = "IDisposableLock"
summary = "Tries to enter the lock in read mode, with an optional integer time-out."
file = "Extensions\\AsyncReaderWriterLockSlimExtension.cs"

[[extensions]]
name = "GetWriteLock"
sig = "IDisposableLock GetWriteLock(this AsyncReaderWriterLockSlim lockInstance,
                                               CancellationToken cancellationToken = default)"
returns = "IDisposableLock"
summary = "Enters the lock in write mode."
file = "Extensions\\AsyncReaderWriterLockSlimExtension.cs"

[[extensions]]
name = "TryGetWriteLock"
sig = "IDisposableLock TryGetWriteLock(this AsyncReaderWriterLockSlim lockInstance,
                                                  int millisecondsTimeout,
                                                  CancellationToken cancellationToken = default)"
returns = "IDisposableLock"
summary = "Tries to enter the lock in write mode, with an optional integer time-out."
file = "Extensions\\AsyncReaderWriterLockSlimExtension.cs"

[[extensions]]
name = "DowngradeWriteLockToReadLock"
sig = "void DowngradeWriteLockToReadLock(this AsyncReaderWriterLockSlim lockInstance,
                                                    IDisposableLock readLock)"
returns = "void"
summary = "Downgrades the lock from write mode to read mode."
file = "Extensions\\AsyncReaderWriterLockSlimExtension.cs"

[[classes]]
name = "EnumerableExtensions"
ns = "FEx.Agnostics.Extensions"
file = "Extensions\\EnumerableExtensions.cs"
static = true

[[extensions]]
name = "OrderAlphanumBy"
sig = "IOrderedEnumerable<string> OrderAlphanumBy(this IEnumerable<string> source)"
returns = "IOrderedEnumerable<string>"
file = "Extensions\\EnumerableExtensions.cs"

[[extensions]]
name = "OrderAlphanumByDescending"
sig = "IOrderedEnumerable<string> OrderAlphanumByDescending(this IEnumerable<string> source)"
returns = "IOrderedEnumerable<string>"
file = "Extensions\\EnumerableExtensions.cs"

[[classes]]
name = "ListExtensions"
ns = "FEx.Agnostics.Extensions"
file = "Extensions\\ListExtensions.cs"
static = true

[[classes]]
name = "ColorHelper"
ns = "FEx.Agnostics.Helpers"
file = "Helpers\\ColorHelper.cs"
static = true

[[classes]]
name = "DeepCopyByExpressionTrees"
ns = "FEx.Agnostics.Helpers"
summary = "Superfast deep copier class, which uses Expression trees."
file = "Helpers\\DeepCopyByExpressionTrees.cs"
static = true

[[classes]]
name = "ReferenceEqualityComparer"
ns = "FEx.Agnostics.Helpers"
base = "EqualityComparer<object>"
file = "Helpers\\DeepCopyByExpressionTrees.cs"

[[classes]]
name = "DefaultAppVersionProvider"
ns = "FEx.Agnostics.Helpers"
base = "IAppVersionProvider"
file = "Helpers\\DefaultAppVersionProvider.cs"

[[classes]]
name = "FindFilesPatternToRegex"
ns = "FEx.Agnostics.Helpers"
file = "Helpers\\FindFilesPatternToRegex.cs"
static = true

[[extensions]]
name = "FindFileEmulator"
sig = "string FindFileEmulator(this string pattern, string name)"
returns = "string"
file = "Helpers\\FindFilesPatternToRegex.cs"

[[extensions]]
name = "FindFilesEmulator"
sig = "IEnumerable<string> FindFilesEmulator(this string pattern, params string[] names)"
returns = "IEnumerable<string>"
file = "Helpers\\FindFilesPatternToRegex.cs"

[[extensions]]
name = "FindFileEmulator"
sig = "FileInfo FindFileEmulator(this FileInfo file, params string[] patterns)"
returns = "FileInfo"
file = "Helpers\\FindFilesPatternToRegex.cs"

[[extensions]]
name = "FindFilesEmulator"
sig = "IEnumerable<FileInfo> FindFilesEmulator(this IEnumerable<FileInfo> files, params string[] patterns)"
returns = "IEnumerable<FileInfo>"
file = "Helpers\\FindFilesPatternToRegex.cs"

[[extensions]]
name = "PathHasIllegalCharacters"
sig = "bool PathHasIllegalCharacters(this string pattern)"
returns = "bool"
file = "Helpers\\FindFilesPatternToRegex.cs"

[[classes]]
name = "StringHelpers"
ns = "FEx.Agnostics.Helpers"
file = "Helpers\\StringHelpers.cs"
static = true

[[classes]]
name = "LoggerState"
ns = "FEx.Agnostics.Models"
base = "Dictionary<string, object>, ILoggerState"
summary = "Default implementation of ILoggerState for structured logging scopes."
file = "Models\\LoggerState.cs"

[[classes]]
name = "AsyncReaderWriterLockSlim"
ns = "FEx.Agnostics.Utilities"
base = "IDisposable"
file = "Utilities\\AsyncReaderWriterLockSlim.cs"

[[classes]]
name = "Cmd"
ns = "FEx.Agnostics.Utilities"
base = "ICmd"
file = "Utilities\\Cmd.cs"

[[classes]]
name = "ExtendedReaderWriterLockSlim"
ns = "FEx.Agnostics.Utilities"
base = "ReaderWriterLockSlim"
file = "Utilities\\ExtendedReaderWriterLockSlim.cs"

[[classes]]
name = "ExtendedStringWriter"
ns = "FEx.Agnostics.Utilities"
base = "StringWriter"
file = "Utilities\\ExtendedStringWriter.cs"

[[classes]]
name = "FExSingleton"
ns = "FEx.Agnostics.Utilities"
base = "IDisposable"
file = "Utilities\\FExSingleton.cs"

[[classes]]
name = "FExSingleton"
ns = "FEx.Agnostics.Utilities"
base = "FExSingleton where T : class, new()"
file = "Utilities\\FExSingleton.cs"

[[classes]]
name = "FlakDynamicObject"
ns = "FEx.Agnostics.Utilities"
base = "DynamicObject, INotifyPropertyChanged"
file = "Utilities\\FlakDynamicObject.cs"

[[interfaces]]
name = "ICmd"
ns = "FEx.Agnostics.Utilities"
file = "Utilities\\ICmd.cs"

[[classes]]
name = "InterlockedBool"
ns = "FEx.Agnostics.Utilities"
file = "Utilities\\InterlockedBool.cs"

