[project]
name = "FEx.AzureStorage"
path = "src\\FEx.AzureStorage"

[[classes]]
name = "AzureStorageConfiguration"
ns = "FEx.AzureStorage"
file = "AzureStorageConfiguration.cs"

[[classes]]
name = "AzureStorageService"
ns = "FEx.AzureStorage"
base = "IAzureStorageService"
file = "AzureStorageService.cs"

[[classes]]
name = "AzureStorageWorker"
ns = "FEx.AzureStorage"
file = "AzureStorageWorker.cs"

[[classes]]
name = "CloudBlockBlobInfo"
ns = "FEx.AzureStorage"
file = "CloudBlockBlobInfo.cs"

[[interfaces]]
name = "IAzureStorageService"
ns = "FEx.AzureStorage"
file = "IAzureStorageService.cs"

[[classes]]
name = "ProgressState"
ns = "FEx.AzureStorage"
file = "ProgressState.cs"

[[enums]]
name = "StorageOperation"
ns = "FEx.AzureStorage"
file = "StorageOperation.cs"

[[classes]]
name = "AzureStorageServiceExtensions"
ns = "FEx.AzureStorage.Extensions"
file = "Extensions\\AzureStorageServiceExtensions.cs"
static = true

[[extensions]]
name = "Configure"
sig = "void Configure(this IAzureStorageService service, string connStr)"
returns = "void"
file = "Extensions\\AzureStorageServiceExtensions.cs"

[[extensions]]
name = "CopyBlobAsync"
sig = "Task<(CloudBlockBlob blob, bool isSuccess)> CopyBlobAsync(
        this IAzureStorageService service,
        string containerName,
        string srcBlob,
        string destBlob)"
returns = "Task<(CloudBlockBlob blob, bool isSuccess)>"
file = "Extensions\\AzureStorageServiceExtensions.cs"

[[extensions]]
name = "DeleteBlobAsync"
sig = "Task<bool> DeleteBlobAsync(this IAzureStorageService service, CloudBlockBlob blob)"
returns = "Task<bool>"
file = "Extensions\\AzureStorageServiceExtensions.cs"

[[extensions]]
name = "DownloadLatestBlobsAsync"
sig = "Task<bool> DownloadLatestBlobsAsync(this IAzureStorageService service,
                                                      string downloadDir,
                                                      string containerName,
                                                      params string[] paths)"
returns = "Task<bool>"
file = "Extensions\\AzureStorageServiceExtensions.cs"

[[extensions]]
name = "ExistsAsync"
sig = "Task<bool> ExistsAsync(this IAzureStorageService service, CloudBlockBlob blob)"
returns = "Task<bool>"
file = "Extensions\\AzureStorageServiceExtensions.cs"

[[extensions]]
name = "ExistsAsync"
sig = "Task<bool> ExistsAsync(this IAzureStorageService service,
                                         string containerName,
                                         string path,
                                         string fileName)"
returns = "Task<bool>"
file = "Extensions\\AzureStorageServiceExtensions.cs"

[[extensions]]
name = "GetBlobAsync"
sig = "Task<CloudBlockBlobInfo> GetBlobAsync(this IAzureStorageService service, string path)"
returns = "Task<CloudBlockBlobInfo>"
file = "Extensions\\AzureStorageServiceExtensions.cs"

[[extensions]]
name = "UploadFileAsync"
sig = "Task<(FileInfo file, CloudBlockBlobInfo blob)> UploadFileAsync(
        this IAzureStorageService service,
        string path,
        bool overwrite,
        FileInfo file)"
returns = "Task<(FileInfo file, CloudBlockBlobInfo blob)>"
file = "Extensions\\AzureStorageServiceExtensions.cs"

[[extensions]]
name = "UploadStreamAsync"
sig = "Task<(string file, CloudBlockBlob blob)> UploadStreamAsync(
        this IAzureStorageService service,
        string path,
        bool overwrite,
        string fileName,
        Stream stream)"
returns = "Task<(string file, CloudBlockBlob blob)>"
file = "Extensions\\AzureStorageServiceExtensions.cs"

[[classes]]
name = "BlobExtensions"
ns = "FEx.AzureStorage.Extensions"
file = "Extensions\\BlobExtensions.cs"
static = true

[[extensions]]
name = "GetBlobChecksum"
sig = "string GetBlobChecksum(this CloudBlockBlob blob)"
returns = "string"
file = "Extensions\\BlobExtensions.cs"

[[extensions]]
name = "GetBlobUri"
sig = "Uri GetBlobUri(this CloudBlockBlob blob)"
returns = "Uri"
file = "Extensions\\BlobExtensions.cs"

[[extensions]]
name = "GetBlobChecksum"
sig = "string GetBlobChecksum(this BlobItem blob)"
returns = "string"
file = "Extensions\\BlobExtensions.cs"

[[extensions]]
name = "GetBlobUri"
sig = "Uri GetBlobUri(this BlobItem blob, BlobContainerClient blobContainerClient)"
returns = "Uri"
file = "Extensions\\BlobExtensions.cs"

