[project]
name = "FEx.CLI"
path = "src\\FEx.CLI"

[[classes]]
name = "CommandLineParserHelper"
ns = "FEx.CLI"
file = "CommandLineParserHelper.cs"
static = true

[[classes]]
name = "ErrorData"
ns = "FEx.CLI"
file = "ErrorData.cs"

