[project]
name = "FEx.Common.Abstractions"
path = "rc\\Common.Abstractions"

[[enums]]
name = "FExNetworkAccess"
ns = "FEx.Common.Abstractions.Enums"
summary = "Various states of the connection to the internet."
file = "Enums\\FExNetworkAccess.cs"

[[classes]]
name = "DeviceHelperExtensions"
ns = "FEx.Common.Abstractions.Extensions"
file = "Extensions\\DeviceHelperExtensions.cs"
static = true

[[extensions]]
name = "WaitForInternetAsync"
sig = "ValueTask<bool> WaitForInternetAsync(this IDeviceHelper helper)"
returns = "ValueTask<bool>"
file = "Extensions\\DeviceHelperExtensions.cs"

[[classes]]
name = "FExInternetConnectionHelperExtensions"
ns = "FEx.Common.Abstractions.Extensions"
file = "Extensions\\FExInternetConnectionHelperExtensions.cs"
static = true

[[extensions]]
name = "HasInternet"
sig = "bool HasInternet(this IFExInternetConnectionHelper helper)"
returns = "bool"
file = "Extensions\\FExInternetConnectionHelperExtensions.cs"

[[classes]]
name = "DateTimeProvider"
ns = "FEx.Common.Abstractions.Helpers"
file = "Helpers\\DateTimeProvider.cs"
static = true

[[classes]]
name = "DateTimeProviderContext"
ns = "FEx.Common.Abstractions.Helpers"
base = "IDisposable"
file = "Helpers\\DateTimeProviderContext.cs"

[[interfaces]]
name = "IConnectivityChangedSubject"
ns = "FEx.Common.Abstractions.Interfaces"
file = "Interfaces\\IConnectivityChangedSubject.cs"

[[interfaces]]
name = "IDeviceHelper"
ns = "FEx.Common.Abstractions.Interfaces"
file = "Interfaces\\IDeviceHelper.cs"

[[interfaces]]
name = "IFExAppSettings"
ns = "FEx.Common.Abstractions.Interfaces"
file = "Interfaces\\IFExAppSettings.cs"

[[interfaces]]
name = "IFExBaseContainer"
ns = "FEx.Common.Abstractions.Interfaces"
file = "Interfaces\\IFExBaseContainer.cs"

[[interfaces]]
name = "IFExCommonContainer"
ns = "FEx.Common.Abstractions.Interfaces"
file = "Interfaces\\IFExCommonContainer.cs"

[[interfaces]]
name = "IFExInternetConnectionHelper"
ns = "FEx.Common.Abstractions.Interfaces"
file = "Interfaces\\IFExInternetConnectionHelper.cs"

[[interfaces]]
name = "IStatusHub"
ns = "FEx.Common.Abstractions.Interfaces"
file = "Interfaces\\IStatusHub.cs"

[[interfaces]]
name = "IStatusService"
ns = "FEx.Common.Abstractions.Interfaces"
file = "Interfaces\\IStatusService.cs"

