[project]
name = "FEx.Common"
path = "src\\Common"

[[classes]]
name = "FExBaseModule"
ns = "FEx.Common"
base = "InitializeModule<IFExBaseContainer, IServiceCollection>"
file = "FExBaseModule.cs"

[[methods]]
parent = "FExBaseModule"
name = "RegisterServices"
sig = "void RegisterServices(IFExBaseContainer container, IServiceCollection context)"
returns = "void"
file = "FExBaseModule.cs"

[[classes]]
name = "FExCommonModule"
ns = "FEx.Common"
base = "InitializeModule<IFExCommonContainer, IServiceCollection>"
file = "FExCommonModule.cs"

[[methods]]
parent = "FExCommonModule"
name = "RegisterServices"
sig = "void RegisterServices(IFExCommonContainer container, IServiceCollection services)"
returns = "void"
file = "FExCommonModule.cs"

[[classes]]
name = "DeviceHelper"
ns = "FEx.Common.Helpers"
base = "IDeviceHelper"
file = "Helpers\\DeviceHelper.cs"

[[properties]]
parent = "DeviceHelper"
name = "HasInternet"
sig = "bool HasInternet { get; }"
returns = "bool"
file = "Helpers\\DeviceHelper.cs"

[[ctors]]
parent = "DeviceHelper"
sig = "DeviceHelper(IConnectivityChangedSubject connectivityChangedSubject)"
file = "Helpers\\DeviceHelper.cs"

[[methods]]
parent = "DeviceHelper"
name = "WaitForInternetAsync"
sig = "ValueTask<bool> WaitForInternetAsync(CancellationToken cancellationToken)"
returns = "ValueTask<bool>"
file = "Helpers\\DeviceHelper.cs"

[[classes]]
name = "FExInternetConnectionHelper"
ns = "FEx.Common.Implementations"
base = "IFExInternetConnectionHelper"
file = "Implementations\\FExInternetConnectionHelper.cs"

[[ctors]]
parent = "FExInternetConnectionHelper"
sig = "FExInternetConnectionHelper(IDeviceHelper deviceHelper, IAsyncHelper asyncHelper)"
file = "Implementations\\FExInternetConnectionHelper.cs"

[[methods]]
parent = "FExInternetConnectionHelper"
name = "HasInternet"
sig = "bool HasInternet(bool triggersCallbackOnLackOfInternet)"
returns = "bool"
file = "Implementations\\FExInternetConnectionHelper.cs"

[[methods]]
parent = "FExInternetConnectionHelper"
name = "OnLackOfInternetAsync"
sig = "Task OnLackOfInternetAsync()"
returns = "Task"
file = "Implementations\\FExInternetConnectionHelper.cs"

[[classes]]
name = "MainThreadDispatcher"
ns = "FEx.Common.Implementations"
base = "FExDispatcher"
file = "Implementations\\MainThreadDispatcher.cs"

[[ctors]]
parent = "MainThreadDispatcher"
sig = "MainThreadDispatcher(IMainThreadContextProvider mainThreadContextProvider, ILogger logger, IDeadlockMonitor deadlockMonitor, IAppThreadingSettings appInstanceSettings, IStackTraceProvider stackTraceProvider)"
file = "Implementations\\MainThreadDispatcher.cs"

[[methods]]
parent = "MainThreadDispatcher"
name = "CheckAccess"
sig = "bool CheckAccess(object sender = null)"
returns = "bool"
file = "Implementations\\MainThreadDispatcher.cs"

[[methods]]
parent = "MainThreadDispatcher"
name = "BeginInvokeOnMainThread"
sig = "void BeginInvokeOnMainThread(Action action, object sender = null)"
returns = "void"
file = "Implementations\\MainThreadDispatcher.cs"

[[methods]]
parent = "MainThreadDispatcher"
name = "InvokeOnMainThreadAsync"
sig = "Task<T> InvokeOnMainThreadAsync<T>(Func<T> action, object sender = null)"
returns = "Task<T>"
file = "Implementations\\MainThreadDispatcher.cs"

[[methods]]
parent = "MainThreadDispatcher"
name = "InvokeOnMainThreadAsync"
sig = "Task InvokeOnMainThreadAsync(Action action, object sender = null)"
returns = "Task"
file = "Implementations\\MainThreadDispatcher.cs"

[[methods]]
parent = "MainThreadDispatcher"
name = "InvokeOnMainThreadAsync"
sig = "Task<T> InvokeOnMainThreadAsync<T>(Func<Task<T>> funcTask, object sender = null)"
returns = "Task<T>"
file = "Implementations\\MainThreadDispatcher.cs"

[[methods]]
parent = "MainThreadDispatcher"
name = "InvokeOnMainThreadAsync"
sig = "Task InvokeOnMainThreadAsync(Func<Task> funcTask, object sender = null)"
returns = "Task"
file = "Implementations\\MainThreadDispatcher.cs"

[[methods]]
parent = "MainThreadDispatcher"
name = "EnableCollectionSynchronization"
sig = "void EnableCollectionSynchronization(IEnumerable collection, object context, Action<IEnumerable, object, Action, bool> callback)"
returns = "void"
file = "Implementations\\MainThreadDispatcher.cs"

[[classes]]
name = "SimpleMainThreadContextProvider"
ns = "FEx.Common.Implementations"
base = "IMainThreadContextProvider"
file = "Implementations\\SimpleMainThreadContextProvider.cs"

[[properties]]
parent = "SimpleMainThreadContextProvider"
name = "Thread"
sig = "Thread Thread { get; }"
returns = "Thread"
file = "Implementations\\SimpleMainThreadContextProvider.cs"

[[properties]]
parent = "SimpleMainThreadContextProvider"
name = "IsDispatcherContext"
sig = "bool IsDispatcherContext { get; set; }"
returns = "bool"
file = "Implementations\\SimpleMainThreadContextProvider.cs"

[[properties]]
parent = "SimpleMainThreadContextProvider"
name = "Context"
sig = "SynchronizationContext Context { get; }"
returns = "SynchronizationContext"
file = "Implementations\\SimpleMainThreadContextProvider.cs"

[[ctors]]
parent = "SimpleMainThreadContextProvider"
sig = "SimpleMainThreadContextProvider()"
file = "Implementations\\SimpleMainThreadContextProvider.cs"

[[methods]]
parent = "SimpleMainThreadContextProvider"
name = "SetMainThread"
sig = "void SetMainThread(bool throwOnNonMainThread = true)"
returns = "void"
file = "Implementations\\SimpleMainThreadContextProvider.cs"

[[classes]]
name = "ConnectivityChangedSubject"
ns = "FEx.Common.Subjects"
base = "FExBehaviorSubject<FExNetworkAccess>, IConnectivityChangedSubject"
file = "Subjects\\ConnectivityChangedSubject.cs"

[[ctors]]
parent = "ConnectivityChangedSubject"
sig = "ConnectivityChangedSubject()"
file = "Subjects\\ConnectivityChangedSubject.cs"

[[ctors]]
parent = "ConnectivityChangedSubject"
sig = "ConnectivityChangedSubject(FExNetworkAccess networkAccess)"
file = "Subjects\\ConnectivityChangedSubject.cs"

