[project]
name = "FEx.Common.Abstractions"
path = "src\\Common.Abstractions"

[[enums]]
name = "FExNetworkAccess"
ns = "FEx.Common.Abstractions.Enums"
summary = "Various states of the connection to the internet."
file = "Enums\\FExNetworkAccess.cs"

[[classes]]
name = "DeviceHelperExtensions"
ns = "FEx.Common.Abstractions.Extensions"
file = "Extensions\\DeviceHelperExtensions.cs"
static = true

[[extensions]]
name = "WaitForInternetAsync"
returns = "ValueTask<bool>"
sig = "ValueTask<bool> WaitForInternetAsync(this IDeviceHelper helper)"
file = "Extensions\\DeviceHelperExtensions.cs"

[[classes]]
name = "FExInternetConnectionHelperExtensions"
ns = "FEx.Common.Abstractions.Extensions"
file = "Extensions\\FExInternetConnectionHelperExtensions.cs"
static = true

[[extensions]]
name = "HasInternet"
returns = "bool"
sig = "bool HasInternet(this IFExInternetConnectionHelper helper)"
file = "Extensions\\FExInternetConnectionHelperExtensions.cs"

[[classes]]
name = "DateTimeProvider"
ns = "FEx.Common.Abstractions.Helpers"
file = "Helpers\\DateTimeProvider.cs"
static = true

[[properties]]
parent = "DateTimeProvider"
name = "Today"
sig = "static DateTime Today { get; }"
returns = "DateTime"
file = "Helpers\\DateTimeProvider.cs"
static = true

[[properties]]
parent = "DateTimeProvider"
name = "Now"
sig = "static DateTime Now { get; }"
returns = "DateTime"
file = "Helpers\\DateTimeProvider.cs"
static = true

[[properties]]
parent = "DateTimeProvider"
name = "UtcNow"
sig = "static DateTime UtcNow { get; }"
returns = "DateTime"
file = "Helpers\\DateTimeProvider.cs"
static = true

[[classes]]
name = "DateTimeProviderContext"
ns = "FEx.Common.Abstractions.Helpers"
base = "IDisposable"
file = "Helpers\\DateTimeProviderContext.cs"

[[properties]]
parent = "DateTimeProviderContext"
name = "Current"
sig = "static DateTimeProviderContext Current { get; }"
returns = "DateTimeProviderContext"
file = "Helpers\\DateTimeProviderContext.cs"
static = true

[[ctors]]
parent = "DateTimeProviderContext"
sig = "DateTimeProviderContext(DateTime contextDateTime)"
file = "Helpers\\DateTimeProviderContext.cs"

[[methods]]
parent = "DateTimeProviderContext"
name = "Dispose"
sig = "void Dispose()"
returns = "void"
file = "Helpers\\DateTimeProviderContext.cs"

[[interfaces]]
name = "IConnectivityChangedSubject"
ns = "FEx.Common.Abstractions.Interfaces"
base = "IFExBehaviorSubject<FExNetworkAccess>"
file = "Interfaces\\IConnectivityChangedSubject.cs"

[[interfaces]]
name = "IDeviceHelper"
ns = "FEx.Common.Abstractions.Interfaces"
file = "Interfaces\\IDeviceHelper.cs"

[[properties]]
parent = "IDeviceHelper"
name = "HasInternet"
sig = "bool HasInternet { get; }"
returns = "bool"
summary = "True if the device is currently connected to the internet."
file = "Interfaces\\IDeviceHelper.cs"

[[methods]]
parent = "IDeviceHelper"
name = "WaitForInternetAsync"
sig = "ValueTask<bool> WaitForInternetAsync(CancellationToken cancellationToken)"
returns = "ValueTask<bool>"
summary = "Waits for a device to be connected to internet, or returns straight away if it already is."
file = "Interfaces\\IDeviceHelper.cs"

[[interfaces]]
name = "IFExAppSettings"
ns = "FEx.Common.Abstractions.Interfaces"
base = "ISentryConfig, IAppThreadingSettings"
file = "Interfaces\\IFExAppSettings.cs"

[[interfaces]]
name = "IFExBaseContainer"
ns = "FEx.Common.Abstractions.Interfaces"
base = "IFExCommonContainer, IFExDependencyInjectionContainer, IFExCoreContainer, IFExLoggingContainer"
file = "Interfaces\\IFExBaseContainer.cs"

[[interfaces]]
name = "IFExCommonContainer"
ns = "FEx.Common.Abstractions.Interfaces"
base = "IContainer<IMainThreadContextProvider>, IContainer<IFExInternetConnectionHelper>, IContainer<IDeviceHelper>, IContainer<IConnectivityChangedSubject>"
file = "Interfaces\\IFExCommonContainer.cs"

[[interfaces]]
name = "IFExInternetConnectionHelper"
ns = "FEx.Common.Abstractions.Interfaces"
file = "Interfaces\\IFExInternetConnectionHelper.cs"

[[methods]]
parent = "IFExInternetConnectionHelper"
name = "HasInternet"
sig = "bool HasInternet(bool triggersCallbackOnLackOfInternet)"
returns = "bool"
summary = "Checks if device is connected to internet and returns straight away if it already is, or executes OnLackOfInternetAsync if not."
file = "Interfaces\\IFExInternetConnectionHelper.cs"

[[interfaces]]
name = "IStatusHub"
ns = "FEx.Common.Abstractions.Interfaces"
file = "Interfaces\\IStatusHub.cs"

[[properties]]
parent = "IStatusHub"
name = "Key"
sig = "Guid Key { get; }"
returns = "Guid"
file = "Interfaces\\IStatusHub.cs"

[[methods]]
parent = "IStatusHub"
name = "AddStatus"
sig = "Guid AddStatus(string status, bool unique = true)"
returns = "Guid"
file = "Interfaces\\IStatusHub.cs"

[[methods]]
parent = "IStatusHub"
name = "AttachToStatusChanges"
sig = "void AttachToStatusChanges(Action<Guid, string> onStatusAdded, Action<Guid, string> onStatusRemoved, Action onStatusesReset)"
returns = "void"
file = "Interfaces\\IStatusHub.cs"

[[methods]]
parent = "IStatusHub"
name = "CleanStatuses"
sig = "void CleanStatuses()"
returns = "void"
file = "Interfaces\\IStatusHub.cs"

[[methods]]
parent = "IStatusHub"
name = "GetStatuses"
sig = "IList<string> GetStatuses()"
returns = "IList<string>"
file = "Interfaces\\IStatusHub.cs"

[[methods]]
parent = "IStatusHub"
name = "GetStatusString"
sig = "string GetStatusString(string separator = null)"
returns = "string"
file = "Interfaces\\IStatusHub.cs"

[[methods]]
parent = "IStatusHub"
name = "RemoveStatus"
sig = "void RemoveStatus(Guid key)"
returns = "void"
file = "Interfaces\\IStatusHub.cs"

[[methods]]
parent = "IStatusHub"
name = "Log"
sig = "DisposableAction Log(string status, bool unique = true)"
returns = "DisposableAction"
file = "Interfaces\\IStatusHub.cs"

[[interfaces]]
name = "IStatusService"
ns = "FEx.Common.Abstractions.Interfaces"
file = "Interfaces\\IStatusService.cs"

[[properties]]
parent = "IStatusService"
name = "MainHub"
sig = "IStatusHub MainHub { get; }"
returns = "IStatusHub"
file = "Interfaces\\IStatusService.cs"

[[properties]]
parent = "IStatusService"
name = "MainHubKey"
sig = "Guid? MainHubKey { get; }"
returns = "Guid?"
file = "Interfaces\\IStatusService.cs"

[[methods]]
parent = "IStatusService"
name = "GetOrAdd"
sig = "IStatusHub GetOrAdd(Guid? key = null, Action<Guid, string> onStatusAdded = null, Action<Guid, string> onStatusRemoved = null, Action onStatusesReset = null, bool markAsMain = false)"
returns = "IStatusHub"
file = "Interfaces\\IStatusService.cs"

[[methods]]
parent = "IStatusService"
name = "LogToMainHub"
sig = "Guid LogToMainHub(string status, bool unique = true)"
returns = "Guid"
file = "Interfaces\\IStatusService.cs"

[[methods]]
parent = "IStatusService"
name = "RemoveMainLog"
sig = "void RemoveMainLog(Guid statusKey)"
returns = "void"
file = "Interfaces\\IStatusService.cs"

[[methods]]
parent = "IStatusService"
name = "Log"
sig = "DisposableAction Log(string status, IStatusHub hub = null, bool unique = true)"
returns = "DisposableAction"
file = "Interfaces\\IStatusService.cs"

