[project]
name = "FEx.Encryption"
path = "src\\FEx.Encryption"

[[classes]]
name = "EncryptionHelper"
ns = "FEx.Encryption"
file = "EncryptionHelper.cs"
static = true

[[methods]]
parent = "EncryptionHelper"
name = "Decode"
sig = "static string Decode(string encryptedInput)"
returns = "string"
file = "EncryptionHelper.cs"
static = true

[[extensions]]
name = "Encode"
returns = "string"
sig = "string Encode(this string valueToEncrypt)"
file = "EncryptionHelper.cs"

[[classes]]
name = "FExEncryption"
ns = "FEx.Encryption"
base = "InitializeOnlyModule"
file = "FExEncryption.cs"

[[properties]]
parent = "FExEncryption"
name = "PassPhrase"
sig = "static string PassPhrase { get; }"
returns = "string"
file = "FExEncryption.cs"
static = true

[[ctors]]
parent = "FExEncryption"
sig = "FExEncryption(IFExEncryptionSettings settings)"
file = "FExEncryption.cs"

[[methods]]
parent = "FExEncryption"
name = "OnInitialize"
sig = "void OnInitialize()"
returns = "void"
file = "FExEncryption.cs"

[[classes]]
name = "FExEncryptionModule"
ns = "FEx.Encryption"
file = "FExEncryptionModule.cs"

[[classes]]
name = "SecureNotifyPropertyChanged"
ns = "FEx.Encryption"
base = "NotifyPropertyChanged"
file = "SecureNotifyPropertyChanged.cs"

[[methods]]
parent = "SecureNotifyPropertyChanged"
name = "IsValid"
sig = "bool IsValid(string propertyName, string decryptedValue)"
returns = "bool"
file = "SecureNotifyPropertyChanged.cs"

[[methods]]
parent = "SecureNotifyPropertyChanged"
name = "DecryptFromSource"
sig = "string DecryptFromSource(ref string source, [CallerMemberName] string propertyName = null)"
returns = "string"
file = "SecureNotifyPropertyChanged.cs"

[[methods]]
parent = "SecureNotifyPropertyChanged"
name = "DecryptFromJsonSource"
sig = "T DecryptFromJsonSource<T>(ref string source, [CallerMemberName] string propertyName = null)"
returns = "T"
file = "SecureNotifyPropertyChanged.cs"

[[methods]]
parent = "SecureNotifyPropertyChanged"
name = "EncryptJsonSource"
sig = "bool EncryptJsonSource<T>(ref string backingField, T newValue, Action<string> onPropertyChanged = null, [CallerMemberName] string propertyName = null)"
returns = "bool"
file = "SecureNotifyPropertyChanged.cs"

[[methods]]
parent = "SecureNotifyPropertyChanged"
name = "EncryptSource"
sig = "bool EncryptSource(ref string backingField, string newValue, Action<string> onPropertyChanged = null, [CallerMemberName] string propertyName = null)"
returns = "bool"
file = "SecureNotifyPropertyChanged.cs"

[[classes]]
name = "StringHasher"
ns = "FEx.Encryption"
file = "StringHasher.cs"
static = true

[[methods]]
parent = "StringHasher"
name = "EncryptString"
sig = "static string EncryptString(string key, string plainInput)"
returns = "string"
file = "StringHasher.cs"
static = true

[[methods]]
parent = "StringHasher"
name = "DecryptString"
sig = "static string DecryptString(string key, string cipherText)"
returns = "string"
file = "StringHasher.cs"
static = true

[[interfaces]]
name = "IFExEncryptionSettings"
ns = "FEx.Encryption.Abstractions.Interfaces"
file = "Abstractions\\Interfaces\\IFExEncryptionSettings.cs"

[[properties]]
parent = "IFExEncryptionSettings"
name = "PassPhrase"
sig = "string PassPhrase { get; }"
returns = "string"
file = "Abstractions\\Interfaces\\IFExEncryptionSettings.cs"

