[project]
name = "FEx.Flurlx.Tests"
path = "test\\FEx.Flurlx.Tests"

[[classes]]
name = "FExPollyPolicyBuilderTests"
ns = "FEx.Flurlx.Tests"
file = "FExPollyPolicyBuilderTests.cs"

[[classes]]
name = "FlurlApiBaseIntegrationTests"
ns = "FEx.Flurlx.Tests"
base = "IDisposable"
file = "FlurlApiBaseIntegrationTests.cs"

