[project]
name = "FEx.Json"
path = "src\\FEx.Json"

[[classes]]
name = "FExJson"
ns = "FEx.Json"
base = "FExInitializable"
file = "FExJson.cs"

[[ctors]]
parent = "FExJson"
sig = "FExJson(IContractResolver contractResolver)"
file = "FExJson.cs"

[[methods]]
parent = "FExJson"
name = "OnInitialize"
sig = "void OnInitialize()"
returns = "void"
file = "FExJson.cs"

[[classes]]
name = "FExJsonModule"
ns = "FEx.Json"
base = "InitializeModule<IFExJsonContainer, IServiceCollection>"
file = "FExJsonModule.cs"

[[methods]]
parent = "FExJsonModule"
name = "JsonSerializerSettingsFactory"
sig = "static JsonSerializerSettings JsonSerializerSettingsFactory()"
returns = "JsonSerializerSettings"
file = "FExJsonModule.cs"
static = true

[[methods]]
parent = "FExJsonModule"
name = "RegisterServices"
sig = "void RegisterServices(IFExJsonContainer container, IServiceCollection services)"
returns = "void"
file = "FExJsonModule.cs"

[[interfaces]]
name = "IFExJsonContainer"
ns = "FEx.Json"
base = "IContainer<FExJson>, IContainer<DIMeta>, IContainer<IContractResolver>, IContainer<JsonSerializerSettings>"
file = "IFExJsonContainer.cs"

[[classes]]
name = "JsonPathConverter"
ns = "FEx.Json.Converters"
base = "JsonConverter"
file = "Converters\\JsonPathConverter.cs"

[[properties]]
parent = "JsonPathConverter"
name = "CanWrite"
sig = "bool CanWrite { get; }"
returns = "bool"
file = "Converters\\JsonPathConverter.cs"

[[methods]]
parent = "JsonPathConverter"
name = "ReadJson"
sig = "object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)"
returns = "object"
file = "Converters\\JsonPathConverter.cs"

[[methods]]
parent = "JsonPathConverter"
name = "CanConvert"
sig = "bool CanConvert(Type objectType)"
returns = "bool"
file = "Converters\\JsonPathConverter.cs"

[[methods]]
parent = "JsonPathConverter"
name = "WriteJson"
sig = "void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)"
returns = "void"
file = "Converters\\JsonPathConverter.cs"

[[classes]]
name = "ParseStringToDoubleConverter"
ns = "FEx.Json.Converters"
base = "JsonConverter"
file = "Converters\\ParseStringToDoubleConverter.cs"

[[properties]]
parent = "ParseStringToDoubleConverter"
name = "Singleton"
sig = "static ParseStringToDoubleConverter Singleton { get; }"
returns = "ParseStringToDoubleConverter"
file = "Converters\\ParseStringToDoubleConverter.cs"
static = true

[[methods]]
parent = "ParseStringToDoubleConverter"
name = "CanConvert"
sig = "bool CanConvert(Type t)"
returns = "bool"
file = "Converters\\ParseStringToDoubleConverter.cs"

[[methods]]
parent = "ParseStringToDoubleConverter"
name = "ReadJson"
sig = "object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)"
returns = "object"
file = "Converters\\ParseStringToDoubleConverter.cs"

[[methods]]
parent = "ParseStringToDoubleConverter"
name = "WriteJson"
sig = "void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)"
returns = "void"
file = "Converters\\ParseStringToDoubleConverter.cs"

[[classes]]
name = "ParseStringToLongConverter"
ns = "FEx.Json.Converters"
base = "JsonConverter"
file = "Converters\\ParseStringToLongConverter.cs"

[[properties]]
parent = "ParseStringToLongConverter"
name = "Singleton"
sig = "static ParseStringToLongConverter Singleton { get; }"
returns = "ParseStringToLongConverter"
file = "Converters\\ParseStringToLongConverter.cs"
static = true

[[methods]]
parent = "ParseStringToLongConverter"
name = "CanConvert"
sig = "bool CanConvert(Type t)"
returns = "bool"
file = "Converters\\ParseStringToLongConverter.cs"

[[methods]]
parent = "ParseStringToLongConverter"
name = "ReadJson"
sig = "object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)"
returns = "object"
file = "Converters\\ParseStringToLongConverter.cs"

[[methods]]
parent = "ParseStringToLongConverter"
name = "WriteJson"
sig = "void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)"
returns = "void"
file = "Converters\\ParseStringToLongConverter.cs"

[[classes]]
name = "JsonExtensions"
ns = "FEx.Json.Extensions"
file = "Extensions\\JsonExtensions.cs"
static = true

[[properties]]
parent = "JsonExtensions"
name = "NullString"
sig = "static string NullString { get; }"
returns = "string"
file = "Extensions\\JsonExtensions.cs"
static = true

[[properties]]
parent = "JsonExtensions"
name = "DefaultSettings"
sig = "static JsonSerializerSettings DefaultSettings { get; }"
returns = "JsonSerializerSettings"
file = "Extensions\\JsonExtensions.cs"
static = true

[[methods]]
parent = "JsonExtensions"
name = "Initialize"
sig = "static void Initialize()"
returns = "void"
file = "Extensions\\JsonExtensions.cs"
static = true

[[methods]]
parent = "JsonExtensions"
name = "ConfigureDefaultSettings"
sig = "static void ConfigureDefaultSettings(Action<JsonSerializerSettings> configuration)"
returns = "void"
file = "Extensions\\JsonExtensions.cs"
static = true

[[extensions]]
name = "ToJson"
returns = "string"
sig = "string ToJson(this object self, JsonSerializerSettings settings, Formatting formatting)"
file = "Extensions\\JsonExtensions.cs"

[[extensions]]
name = "ToJson"
returns = "string"
sig = "string ToJson(this object self)"
file = "Extensions\\JsonExtensions.cs"

[[extensions]]
name = "ToJson"
returns = "string"
sig = "string ToJson(this object self, JsonSerializerSettings settings)"
file = "Extensions\\JsonExtensions.cs"

[[extensions]]
name = "ToJson"
returns = "string"
sig = "string ToJson(this object self, Formatting formatting)"
file = "Extensions\\JsonExtensions.cs"

[[extensions]]
name = "FromJson"
returns = "T"
sig = "T FromJson<T>(this string json, JsonSerializerSettings settings, T fallback)"
file = "Extensions\\JsonExtensions.cs"

[[extensions]]
name = "FromJson"
returns = "T"
sig = "T FromJson<T>(this string json)"
file = "Extensions\\JsonExtensions.cs"

[[extensions]]
name = "FromJson"
returns = "T"
sig = "T FromJson<T>(this string json, JsonSerializerSettings settings)"
file = "Extensions\\JsonExtensions.cs"

[[extensions]]
name = "FromJson"
returns = "object"
sig = "object FromJson(this string json, JsonSerializerSettings settings)"
file = "Extensions\\JsonExtensions.cs"

[[extensions]]
name = "FromJson"
returns = "object"
sig = "object FromJson(this string json)"
file = "Extensions\\JsonExtensions.cs"

[[extensions]]
name = "DeserializeFromStream"
returns = "object"
sig = "object DeserializeFromStream(this Stream stream, JsonSerializerSettings settings)"
file = "Extensions\\JsonExtensions.cs"

[[extensions]]
name = "DeserializeFromStream"
returns = "object"
sig = "object DeserializeFromStream(this Stream stream)"
file = "Extensions\\JsonExtensions.cs"

[[extensions]]
name = "DeserializeFromStream"
returns = "T"
sig = "T DeserializeFromStream<T>(this Stream stream, JsonSerializerSettings settings)"
file = "Extensions\\JsonExtensions.cs"

[[extensions]]
name = "DeserializeFromStream"
returns = "T"
sig = "T DeserializeFromStream<T>(this Stream stream)"
file = "Extensions\\JsonExtensions.cs"

[[extensions]]
name = "ReformatJson"
returns = "string"
sig = "string ReformatJson(this string json)"
summary = "Reformats the json."
file = "Extensions\\JsonExtensions.cs"

[[extensions]]
name = "DeserializeToken"
returns = "T"
sig = "T DeserializeToken<T>(this JToken jToken, JsonSerializerSettings settings)"
summary = "Deserializes the token."
file = "Extensions\\JsonExtensions.cs"

[[extensions]]
name = "DeserializeToken"
returns = "T"
sig = "T DeserializeToken<T>(this JToken jToken)"
file = "Extensions\\JsonExtensions.cs"

[[extensions]]
name = "TrimJsonString"
returns = "string"
sig = "string TrimJsonString(this string jsonValue)"
file = "Extensions\\JsonExtensions.cs"

[[methods]]
parent = "JsonExtensions"
name = "PrettyPrintFile"
sig = "static void PrettyPrintFile(string orgPath, string destPath)"
returns = "void"
file = "Extensions\\JsonExtensions.cs"
static = true

[[extensions]]
name = "PrettyPrintJson"
returns = "string"
sig = "string PrettyPrintJson(this string json, JsonLoadSettings loadSettings, JsonSerializerSettings saveSettings, Formatting formatting)"
file = "Extensions\\JsonExtensions.cs"

[[extensions]]
name = "PrettyPrintJson"
returns = "string"
sig = "string PrettyPrintJson(this string json)"
file = "Extensions\\JsonExtensions.cs"

[[extensions]]
name = "PrettyPrintJson"
returns = "string"
sig = "string PrettyPrintJson(this string json, JsonLoadSettings loadSettings)"
file = "Extensions\\JsonExtensions.cs"

[[extensions]]
name = "PrettyPrintJson"
returns = "string"
sig = "string PrettyPrintJson(this string json, JsonLoadSettings loadSettings, JsonSerializerSettings saveSettings)"
file = "Extensions\\JsonExtensions.cs"

[[extensions]]
name = "DeserializeFromFile"
returns = "T"
sig = "T DeserializeFromFile<T>(this FileInfo file, JsonSerializerSettings settings)"
file = "Extensions\\JsonExtensions.cs"

[[extensions]]
name = "DeserializeFromFile"
returns = "T"
sig = "T DeserializeFromFile<T>(this FileInfo file)"
file = "Extensions\\JsonExtensions.cs"

[[extensions]]
name = "SerializeToFile"
returns = "void"
sig = "void SerializeToFile(this FileInfo file, object self, JsonSerializerSettings settings, Formatting formatting)"
file = "Extensions\\JsonExtensions.cs"

[[extensions]]
name = "SerializeToFile"
returns = "void"
sig = "void SerializeToFile(this FileInfo file, object self)"
file = "Extensions\\JsonExtensions.cs"

[[extensions]]
name = "SerializeToFile"
returns = "void"
sig = "void SerializeToFile(this FileInfo file, object self, JsonSerializerSettings settings)"
file = "Extensions\\JsonExtensions.cs"

[[classes]]
name = "NotifyPropertyChangedExtensions"
ns = "FEx.Json.Extensions"
file = "Extensions\\NotifyPropertyChangedExtensions.cs"
static = true

[[extensions]]
name = "SetPropertyAndDeserializeIt"
returns = "bool"
sig = "bool SetPropertyAndDeserializeIt<TEntity>(this IFExNotifyPropertyChanged obj, ref string backingField, string jsonValue, Action<TEntity> onDeserializedAction = null, JsonSerializerSettings settings = null, [CallerMemberName] string propertyName = null)"
file = "Extensions\\NotifyPropertyChangedExtensions.cs"

[[classes]]
name = "DIMeta"
ns = "FEx.Json.Helpers"
base = "InitializeOnlyModule"
file = "Helpers\\DIMeta.cs"

[[ctors]]
parent = "DIMeta"
sig = "DIMeta()"
file = "Helpers\\DIMeta.cs"

[[methods]]
parent = "DIMeta"
name = "OnCompleteInitializationAsync"
sig = "ValueTask OnCompleteInitializationAsync(IServiceCollection services)"
returns = "ValueTask"
file = "Helpers\\DIMeta.cs"

[[methods]]
parent = "DIMeta"
name = "IsRegistred"
sig = "bool IsRegistred(Type t)"
returns = "bool"
file = "Helpers\\DIMeta.cs"

[[methods]]
parent = "DIMeta"
name = "RegistredTypeFor"
sig = "Type RegistredTypeFor(Type t)"
returns = "Type"
file = "Helpers\\DIMeta.cs"

[[methods]]
parent = "DIMeta"
name = "RegisterServices"
sig = "void RegisterServices(object container, IServiceCollection services)"
returns = "void"
file = "Helpers\\DIMeta.cs"

[[classes]]
name = "DIContractResolver"
ns = "FEx.Json.Resolvers"
base = "DefaultContractResolver"
file = "Resolvers\\DIContractResolver.cs"

[[ctors]]
parent = "DIContractResolver"
sig = "DIContractResolver(DIMeta diMeta)"
file = "Resolvers\\DIContractResolver.cs"

[[methods]]
parent = "DIContractResolver"
name = "CreateObjectContract"
sig = "JsonObjectContract CreateObjectContract(Type objectType)"
returns = "JsonObjectContract"
file = "Resolvers\\DIContractResolver.cs"

[[classes]]
name = "PropertyRenameAndIgnoreSerializerContractResolver"
ns = "FEx.Json.Resolvers"
base = "DefaultContractResolver"
file = "Resolvers\\PropertyRenameAndIgnoreSerializerContractResolver.cs"

[[ctors]]
parent = "PropertyRenameAndIgnoreSerializerContractResolver"
sig = "PropertyRenameAndIgnoreSerializerContractResolver()"
file = "Resolvers\\PropertyRenameAndIgnoreSerializerContractResolver.cs"

[[methods]]
parent = "PropertyRenameAndIgnoreSerializerContractResolver"
name = "IgnoreProperty"
sig = "void IgnoreProperty(Type type, params string[] jsonPropertyNames)"
returns = "void"
file = "Resolvers\\PropertyRenameAndIgnoreSerializerContractResolver.cs"

[[methods]]
parent = "PropertyRenameAndIgnoreSerializerContractResolver"
name = "RenameProperty"
sig = "void RenameProperty(Type type, string propertyName, string newJsonPropertyName)"
returns = "void"
file = "Resolvers\\PropertyRenameAndIgnoreSerializerContractResolver.cs"

[[methods]]
parent = "PropertyRenameAndIgnoreSerializerContractResolver"
name = "CreateProperty"
sig = "JsonProperty CreateProperty(MemberInfo member, MemberSerialization memberSerialization)"
returns = "JsonProperty"
file = "Resolvers\\PropertyRenameAndIgnoreSerializerContractResolver.cs"

