[project]
name = "FEx.Maui"
path = "src\\FEx.Maui"

[[classes]]
name = "FExMauiDispatcher"
ns = "FEx.Maui"
base = "FExDispatcher"
file = "FExMauiDispatcher.cs"

[[ctors]]
parent = "FExMauiDispatcher"
sig = "FExMauiDispatcher(ILogger logger, IMainThreadContextProvider mainThreadContextProvider, IDeadlockMonitor deadlockMonitor, IStackTraceProvider stackTraceProvider)"
file = "FExMauiDispatcher.cs"

[[ctors]]
parent = "FExMauiDispatcher"
sig = "FExMauiDispatcher(ILogger logger, IMainThreadContextProvider mainThreadContextProvider, IDeadlockMonitor deadlockMonitor, IStackTraceProvider stackTraceProvider, bool isDeadlockMonitoringEnabled)"
file = "FExMauiDispatcher.cs"

[[methods]]
parent = "FExMauiDispatcher"
name = "BeginInvokeOnMainThread"
sig = "void BeginInvokeOnMainThread(Action action, object sender)"
returns = "void"
file = "FExMauiDispatcher.cs"

[[methods]]
parent = "FExMauiDispatcher"
name = "InvokeOnMainThreadAsync"
sig = "Task InvokeOnMainThreadAsync(Action action, object sender)"
returns = "Task"
file = "FExMauiDispatcher.cs"

[[methods]]
parent = "FExMauiDispatcher"
name = "InvokeOnMainThreadAsync"
sig = "Task<T> InvokeOnMainThreadAsync<T>(Func<T> func, object sender)"
returns = "Task<T>"
file = "FExMauiDispatcher.cs"

[[methods]]
parent = "FExMauiDispatcher"
name = "InvokeOnMainThreadAsync"
sig = "Task<T> InvokeOnMainThreadAsync<T>(Func<Task<T>> funcTask, object sender)"
returns = "Task<T>"
file = "FExMauiDispatcher.cs"

[[methods]]
parent = "FExMauiDispatcher"
name = "InvokeOnMainThreadAsync"
sig = "Task InvokeOnMainThreadAsync(Func<Task> funcTask, object sender)"
returns = "Task"
file = "FExMauiDispatcher.cs"

[[methods]]
parent = "FExMauiDispatcher"
name = "CheckAccess"
sig = "bool CheckAccess(object sender)"
returns = "bool"
file = "FExMauiDispatcher.cs"

[[methods]]
parent = "FExMauiDispatcher"
name = "EnableCollectionSynchronization"
sig = "void EnableCollectionSynchronization(IEnumerable collection, object context, Action<IEnumerable, object, Action, bool> callback)"
returns = "void"
file = "FExMauiDispatcher.cs"

