[project]
name = "FEx.MVVM.Tests"
path = "test\\FEx.MVVM.Tests"

[[classes]]
name = "LinkedPropertiesTests"
ns = "FEx.MVVM.Tests"
file = "LinkedPropertiesTests.cs"

[[classes]]
name = "Child"
ns = "FEx.MVVM.Tests"
base = "LinkableNotifyPropertyChanged"
file = "LinkedPropertiesTests.cs"

[[classes]]
name = "ChildInfo"
ns = "FEx.MVVM.Tests"
base = "LinkableNotifyPropertyChanged"
file = "LinkedPropertiesTests.cs"

[[classes]]
name = "SingleParent"
ns = "FEx.MVVM.Tests"
base = "LinkableNotifyPropertyChanged"
file = "LinkedPropertiesTests.cs"

[[classes]]
name = "TestableProgressAggregator"
ns = "FEx.MVVM.Tests"
base = "ProgressAggregator"
file = "ProgressAggregatorTests.cs"

[[classes]]
name = "ProgressAggregatorTests"
ns = "FEx.MVVM.Tests"
file = "ProgressAggregatorTests.cs"

[[classes]]
name = "ProgressServiceTests"
ns = "FEx.MVVM.Tests"
file = "ProgressServiceTests.cs"

