[project]
name = "FEx.MVVM.Abstractions"
path = "src\\FEx.MVVM.Abstractions"

[[classes]]
name = "DummyPopupService"
ns = "FEx.MVVM.Abstractions"
base = "IMessagePopupService"
file = "DummyPopupService.cs"

[[classes]]
name = "FExTreeViewNode"
ns = "FEx.MVVM.Abstractions"
base = "IEquatable<FExTreeViewNode>"
file = "FExTreeViewNode.cs"

[[classes]]
name = "LinkableNotifyPropertyChanged"
ns = "FEx.MVVM.Abstractions"
base = "NotifyPropertyChanged, ILinkableNotifyPropertyChanged"
file = "LinkableNotifyPropertyChanged.cs"

[[classes]]
name = "LinkManager"
ns = "FEx.MVVM.Abstractions"
file = "LinkManager.cs"

[[classes]]
name = "WidthAndHeight"
ns = "FEx.MVVM.Abstractions"
base = "IComparable<WidthAndHeight>, IEquatable<WidthAndHeight>"
file = "WidthAndHeight.cs"

[[classes]]
name = "DialogOptionsBase"
ns = "FEx.MVVM.Abstractions.Dialogs"
file = "Dialogs\\DialogOptionsBase.cs"

[[classes]]
name = "FileDialogOptionsBase"
ns = "FEx.MVVM.Abstractions.Dialogs"
base = "DialogOptionsBase<TDialog>"
file = "Dialogs\\FileDialogOptionsBase.cs"

[[classes]]
name = "FolderBrowserDialogOptionsBase"
ns = "FEx.MVVM.Abstractions.Dialogs"
base = "DialogOptionsBase<TDialog>"
file = "Dialogs\\FolderBrowserDialogOptionsBase.cs"

[[classes]]
name = "OpenFileDialogOptionsBase"
ns = "FEx.MVVM.Abstractions.Dialogs"
base = "FileDialogOptionsBase<TDialog>"
file = "Dialogs\\OpenFileDialogOptionsBase.cs"

[[classes]]
name = "SaveFileDialogOptionsBase"
ns = "FEx.MVVM.Abstractions.Dialogs"
base = "FileDialogOptionsBase<TDialog>"
file = "Dialogs\\SaveFileDialogOptionsBase.cs"

[[enums]]
name = "FExMessageButton"
ns = "FEx.MVVM.Abstractions.Enums"
summary = "Specifies the buttons that are displayed on a message box."
file = "Enums\\FExMessageButton.cs"

[[enums]]
name = "MessageIcon"
ns = "FEx.MVVM.Abstractions.Enums"
file = "Enums\\MessageIcon.cs"

[[enums]]
name = "MessageResult"
ns = "FEx.MVVM.Abstractions.Enums"
summary = "Specifies which message box button that a user clicks."
file = "Enums\\MessageResult.cs"

[[enums]]
name = "ProgressChangeMode"
ns = "FEx.MVVM.Abstractions.Enums"
file = "Enums\\ProgressChangeMode.cs"

[[enums]]
name = "ProgressOperationMode"
ns = "FEx.MVVM.Abstractions.Enums"
file = "Enums\\ProgressOperationMode.cs"

[[enums]]
name = "ProgressState"
ns = "FEx.MVVM.Abstractions.Enums"
file = "Enums\\ProgressState.cs"

[[classes]]
name = "ProgressPropertyChangedEventArgs"
ns = "FEx.MVVM.Abstractions.Events"
base = "EventArgs"
file = "Events\\ProgressPropertyChangedEventArgs.cs"

[[classes]]
name = "FExTimerExtensions"
ns = "FEx.MVVM.Abstractions.Extensions"
file = "Extensions\\FExTimerExtensions.cs"
static = true

[[extensions]]
name = "WithAsyncCallback"
sig = "IFExTimer WithAsyncCallback(this IFExTimer timer, Func<Task> asyncCallback)"
returns = "IFExTimer"
file = "Extensions\\FExTimerExtensions.cs"

[[classes]]
name = "LinkableNotifyPropertyChangedExtensions"
ns = "FEx.MVVM.Abstractions.Extensions"
file = "Extensions\\LinkableNotifyPropertyChangedExtensions.cs"
static = true

[[extensions]]
name = "Unlink"
sig = "void Unlink(this ILinkableNotifyPropertyChanged source, ILink link)"
returns = "void"
file = "Extensions\\LinkableNotifyPropertyChangedExtensions.cs"

[[extensions]]
name = "Unlink"
sig = "void Unlink(this ILinkableNotifyPropertyChanged source, Guid linkId, string propertyName, Type propertyType)"
returns = "void"
file = "Extensions\\LinkableNotifyPropertyChangedExtensions.cs"

[[classes]]
name = "MessagePopupServiceExtensions"
ns = "FEx.MVVM.Abstractions.Extensions"
file = "Extensions\\MessagePopupServiceExtensions.cs"
static = true

[[extensions]]
name = "ShowMessageAsync"
sig = "Task<MessageResult> ShowMessageAsync(this IMessagePopupService service, string txt)"
returns = "Task<MessageResult>"
file = "Extensions\\MessagePopupServiceExtensions.cs"

[[extensions]]
name = "ShowMessageAsync"
sig = "Task<MessageResult> ShowMessageAsync(this IMessagePopupService service, string txt, string caption)"
returns = "Task<MessageResult>"
file = "Extensions\\MessagePopupServiceExtensions.cs"

[[extensions]]
name = "ShowMessageAsync"
sig = "Task<MessageResult> ShowMessageAsync(this IMessagePopupService service, string txt, string caption, MessageIcon messageBoxImage)"
returns = "Task<MessageResult>"
file = "Extensions\\MessagePopupServiceExtensions.cs"

[[extensions]]
name = "ShowMessageAsync"
sig = "Task<MessageResult> ShowMessageAsync(this IMessagePopupService service, string txt, string caption, MessageIcon messageBoxImage, FExMessageButton button)"
returns = "Task<MessageResult>"
file = "Extensions\\MessagePopupServiceExtensions.cs"

[[extensions]]
name = "ShowMessage"
sig = "MessageResult ShowMessage(this IMessagePopupService service, string txt)"
returns = "MessageResult"
file = "Extensions\\MessagePopupServiceExtensions.cs"

[[extensions]]
name = "ShowMessage"
sig = "MessageResult ShowMessage(this IMessagePopupService service, string txt, string caption)"
returns = "MessageResult"
file = "Extensions\\MessagePopupServiceExtensions.cs"

[[extensions]]
name = "ShowMessage"
sig = "MessageResult ShowMessage(this IMessagePopupService service, string txt, string caption, MessageIcon messageBoxImage)"
returns = "MessageResult"
file = "Extensions\\MessagePopupServiceExtensions.cs"

[[extensions]]
name = "ShowMessage"
sig = "MessageResult ShowMessage(this IMessagePopupService service, string txt, string caption, MessageIcon messageBoxImage, FExMessageButton button)"
returns = "MessageResult"
file = "Extensions\\MessagePopupServiceExtensions.cs"

[[classes]]
name = "ProgressAggregatorExtensions"
ns = "FEx.MVVM.Abstractions.Extensions"
file = "Extensions\\ProgressAggregatorExtensions.cs"
static = true

[[extensions]]
name = "PrgSet"
sig = "void PrgSet(this IProgressAggregator aggregator, double? value)"
returns = "void"
file = "Extensions\\ProgressAggregatorExtensions.cs"

[[extensions]]
name = "PrgSet"
sig = "void PrgSet(this IProgressAggregator aggregator, double? value, double? maximum)"
returns = "void"
file = "Extensions\\ProgressAggregatorExtensions.cs"

[[extensions]]
name = "PrgAdd"
sig = "void PrgAdd(this IProgressAggregator aggregator)"
returns = "void"
file = "Extensions\\ProgressAggregatorExtensions.cs"

[[interfaces]]
name = "IAsyncCommand"
ns = "FEx.MVVM.Abstractions.Interfaces"
file = "Interfaces\\IAsyncCommand.cs"

[[interfaces]]
name = "IAsyncCommand"
ns = "FEx.MVVM.Abstractions.Interfaces"
file = "Interfaces\\IAsyncCommand.cs"

[[interfaces]]
name = "IFExTimer"
ns = "FEx.MVVM.Abstractions.Interfaces"
file = "Interfaces\\IFExTimer.cs"

[[interfaces]]
name = "ILink"
ns = "FEx.MVVM.Abstractions.Interfaces"
file = "Interfaces\\ILink.cs"

[[interfaces]]
name = "ILinkableNotifyPropertyChanged"
ns = "FEx.MVVM.Abstractions.Interfaces"
file = "Interfaces\\ILinkableNotifyPropertyChanged.cs"

[[interfaces]]
name = "IMessagePopupService"
ns = "FEx.MVVM.Abstractions.Interfaces"
file = "Interfaces\\IMessagePopupService.cs"

[[interfaces]]
name = "IProgressAggregator"
ns = "FEx.MVVM.Abstractions.Interfaces"
file = "Interfaces\\IProgressAggregator.cs"

[[interfaces]]
name = "IProgressNotifyPropertyChanged"
ns = "FEx.MVVM.Abstractions.Interfaces"
file = "Interfaces\\IProgressNotifyPropertyChanged.cs"

[[interfaces]]
name = "IProgressStatus"
ns = "FEx.MVVM.Abstractions.Interfaces"
file = "Interfaces\\IProgressStatus.cs"

[[interfaces]]
name = "IViewModelBase"
ns = "FEx.MVVM.Abstractions.Interfaces"
file = "Interfaces\\IViewModelBase.cs"

