[project]
name = "FEx.NuGetx"
path = "src\\FEx.NuGetx"

[[interfaces]]
name = "INuGetExModule"
ns = "FEx.NuGetx"
base = "IContainer<NuGetEx>, IContainer<NuGetManager>, IContainer<NuGetLogger<NuGetManager>>"
file = "INuGetExModule.cs"

[[classes]]
name = "NuGetEx"
ns = "FEx.NuGetx"
base = "InitializeModule<INuGetExModule, IServiceCollection>"
file = "NuGetEx.cs"

[[methods]]
parent = "NuGetEx"
name = "RegisterServices"
sig = "void RegisterServices(INuGetExModule container, IServiceCollection services)"
returns = "void"
file = "NuGetEx.cs"

[[classes]]
name = "NuGetExModule"
ns = "FEx.NuGetx"
file = "NuGetExModule.cs"

[[methods]]
parent = "NuGetExModule"
name = "AddServices"
sig = "static void AddServices(INuGetExModule container, IServiceCollection services)"
returns = "void"
file = "NuGetExModule.cs"
static = true

[[classes]]
name = "NuGetLogger"
ns = "FEx.NuGetx"
base = "INuGetLogger"
file = "NuGetLogger.cs"

[[ctors]]
parent = "NuGetLogger"
sig = "NuGetLogger(ILogger<T> logger)"
file = "NuGetLogger.cs"

[[methods]]
parent = "NuGetLogger"
name = "LogDebug"
sig = "void LogDebug(string data)"
returns = "void"
file = "NuGetLogger.cs"

[[methods]]
parent = "NuGetLogger"
name = "LogVerbose"
sig = "void LogVerbose(string data)"
returns = "void"
file = "NuGetLogger.cs"

[[methods]]
parent = "NuGetLogger"
name = "LogInformation"
sig = "void LogInformation(string data)"
returns = "void"
file = "NuGetLogger.cs"

[[methods]]
parent = "NuGetLogger"
name = "LogMinimal"
sig = "void LogMinimal(string data)"
returns = "void"
file = "NuGetLogger.cs"

[[methods]]
parent = "NuGetLogger"
name = "LogWarning"
sig = "void LogWarning(string data)"
returns = "void"
file = "NuGetLogger.cs"

[[methods]]
parent = "NuGetLogger"
name = "LogError"
sig = "void LogError(string data)"
returns = "void"
file = "NuGetLogger.cs"

[[methods]]
parent = "NuGetLogger"
name = "LogInformationSummary"
sig = "void LogInformationSummary(string data)"
returns = "void"
file = "NuGetLogger.cs"

[[methods]]
parent = "NuGetLogger"
name = "Log"
sig = "void Log(NuGetLogLevel level, string data)"
returns = "void"
file = "NuGetLogger.cs"

[[methods]]
parent = "NuGetLogger"
name = "Log"
sig = "void Log(ILogMessage message)"
returns = "void"
file = "NuGetLogger.cs"

[[methods]]
parent = "NuGetLogger"
name = "LogAsync"
sig = "Task LogAsync(NuGetLogLevel level, string data)"
returns = "Task"
file = "NuGetLogger.cs"

[[methods]]
parent = "NuGetLogger"
name = "LogAsync"
sig = "Task LogAsync(ILogMessage message)"
returns = "Task"
file = "NuGetLogger.cs"

[[methods]]
parent = "NuGetLogger"
name = "LogSummary"
sig = "void LogSummary(string data)"
returns = "void"
file = "NuGetLogger.cs"

[[methods]]
parent = "NuGetLogger"
name = "Dump"
sig = "void Dump(LogLevel logLevel, string content)"
returns = "void"
file = "NuGetLogger.cs"

[[classes]]
name = "NuGetManager"
ns = "FEx.NuGetx"
base = "AsyncInitializable"
file = "NuGetManager.cs"

[[ctors]]
parent = "NuGetManager"
sig = "NuGetManager(NuGetLogger<NuGetManager> logger)"
file = "NuGetManager.cs"

[[methods]]
parent = "NuGetManager"
name = "GetNuGetOrgPackageMetadataResourceAsync"
sig = "static Task<PackageMetadataResource> GetNuGetOrgPackageMetadataResourceAsync()"
returns = "Task<PackageMetadataResource>"
file = "NuGetManager.cs"
static = true

[[methods]]
parent = "NuGetManager"
name = "GetIdentitiesAsync"
sig = "static Task<PackageIdentity[]> GetIdentitiesAsync( PackageSearchMetadataBuilder.ClonedPackageSearchMetadata package)"
returns = "Task<PackageIdentity[]>"
file = "NuGetManager.cs"
static = true

[[methods]]
parent = "NuGetManager"
name = "GetPackageDependenciesAsync"
sig = "static Task GetPackageDependenciesAsync(PackageIdentity package, NuGetFramework framework, SourceCacheContext cacheContext, INuGetLogger logger, IEnumerable<SourceRepository> repositories, ISet<SourcePackageDependencyInfo> availablePackages)"
returns = "Task"
file = "NuGetManager.cs"
static = true

[[methods]]
parent = "NuGetManager"
name = "BackupPackageAsync"
sig = "Task BackupPackageAsync(PackageIdentity package, DirectoryInfo backupDirectory, int allPackagesCount, ISettings settings, DownloadResource downloadResource, SourceCacheContext cacheContext, CancellationToken token)"
returns = "Task"
file = "NuGetManager.cs"

[[methods]]
parent = "NuGetManager"
name = "RestorePackageByIdAsync"
sig = "Task<(DownloadResourceResult result, bool isSuccess)> RestorePackageByIdAsync( string packageId, bool includePrerelease = false, bool includeUnlisted = false, CancellationToken token = default)"
returns = "Task<(DownloadResourceResult result, bool isSuccess)>"
file = "NuGetManager.cs"

[[methods]]
parent = "NuGetManager"
name = "UnlistAllPackageVersionsAsync"
sig = "Task UnlistAllPackageVersionsAsync(string packageId, PackageMetadataResource packageMetadataResource, SourceCacheContext sourceCacheContext, string apiKey)"
returns = "Task"
file = "NuGetManager.cs"

[[methods]]
parent = "NuGetManager"
name = "DeletePackageAsync"
sig = "Task<bool> DeletePackageAsync(PackageSearchMetadataRegistration pkgToDel, string apiKey)"
returns = "Task<bool>"
file = "NuGetManager.cs"

[[methods]]
parent = "NuGetManager"
name = "RestorePackageAsync"
sig = "Task<(DownloadResourceResult result, bool isSuccess)> RestorePackageAsync( PackageIdentity pkgToRestore, DownloadResource downloadResource, SourceCacheContext sourceCacheContext, ISettings settings, bool directDownload = false, string directDownloadDirectory = null)"
returns = "Task<(DownloadResourceResult result, bool isSuccess)>"
file = "NuGetManager.cs"

[[methods]]
parent = "NuGetManager"
name = "GetNuGetsToPublishOnNuGetOrgAsync"
sig = "Task<FileInfo[]> GetNuGetsToPublishOnNuGetOrgAsync(FileInfo[] allNuGets, HashSet<string> excludedPackageNames = null, params string[] packagesToPublish)"
returns = "Task<FileInfo[]>"
file = "NuGetManager.cs"

[[methods]]
parent = "NuGetManager"
name = "GetNuGetsToPublishAsync"
sig = "Task<FileInfo[]> GetNuGetsToPublishAsync(PackageMetadataResource packageMetadataResource, FileInfo[] allNuGets, HashSet<string> excludedPackageNames = null, params string[] packagesToPublish)"
returns = "Task<FileInfo[]>"
file = "NuGetManager.cs"

[[methods]]
parent = "NuGetManager"
name = "OnInitializeAsync"
sig = "Task OnInitializeAsync()"
returns = "Task"
file = "NuGetManager.cs"

[[classes]]
name = "NuGetPackageInstallation"
ns = "FEx.NuGetx"
base = "NotifyPropertyChanged"
file = "NuGetPackageInstallation.cs"

[[properties]]
parent = "NuGetPackageInstallation"
name = "Name"
sig = "string Name { get; }"
returns = "string"
file = "NuGetPackageInstallation.cs"

[[properties]]
parent = "NuGetPackageInstallation"
name = "Version"
sig = "string Version { get; }"
returns = "string"
file = "NuGetPackageInstallation.cs"

[[properties]]
parent = "NuGetPackageInstallation"
name = "Url"
sig = "Uri Url { get; }"
returns = "Uri"
file = "NuGetPackageInstallation.cs"

[[ctors]]
parent = "NuGetPackageInstallation"
sig = "NuGetPackageInstallation(PackageIdentity package)"
file = "NuGetPackageInstallation.cs"

