[project]
name = "FEx.PersistentStorage.Rx"
path = "src\\PersistentStorage.Rx"

[[classes]]
name = "AggregatedCollectionCachedSubject"
ns = "FEx.PersistentStorage.Rx.Subjects"
base = "CollectionCachedSubject<T, TCacheable>"
file = "Subjects\\AggregatedCollectionCachedSubject.cs"

[[ctors]]
parent = "AggregatedCollectionCachedSubject"
sig = "AggregatedCollectionCachedSubject(ICacheService cacheService, ClearCacheReason clearCacheReason)"
file = "Subjects\\AggregatedCollectionCachedSubject.cs"

[[methods]]
parent = "AggregatedCollectionCachedSubject"
name = "OnReset"
sig = "void OnReset(IEnumerable<T> newCollection)"
returns = "void"
file = "Subjects\\AggregatedCollectionCachedSubject.cs"

[[methods]]
parent = "AggregatedCollectionCachedSubject"
name = "OnNext"
sig = "void OnNext(IReadOnlyCollection<T> value)"
returns = "void"
file = "Subjects\\AggregatedCollectionCachedSubject.cs"

[[classes]]
name = "CachedSubjectBase"
ns = "FEx.PersistentStorage.Rx.Subjects"
base = "FExBehaviorSubject<TData>, IClearCache, IRequiresInitialization"
file = "Subjects\\CachedSubjectBase.cs"

[[properties]]
parent = "CachedSubjectBase"
name = "ClearCacheReason"
sig = "ClearCacheReason ClearCacheReason { get; }"
returns = "ClearCacheReason"
file = "Subjects\\CachedSubjectBase.cs"

[[ctors]]
parent = "CachedSubjectBase"
sig = "CachedSubjectBase(ICacheService cacheService, ClearCacheReason clearCacheReason)"
file = "Subjects\\CachedSubjectBase.cs"

[[ctors]]
parent = "CachedSubjectBase"
sig = "CachedSubjectBase(ICacheService cacheService, ClearCacheReason clearCacheReason, TData defaultValue)"
file = "Subjects\\CachedSubjectBase.cs"

[[methods]]
parent = "CachedSubjectBase"
name = "ClearCache"
sig = "void ClearCache()"
returns = "void"
file = "Subjects\\CachedSubjectBase.cs"

[[methods]]
parent = "CachedSubjectBase"
name = "Initialize"
sig = "void Initialize()"
returns = "void"
file = "Subjects\\CachedSubjectBase.cs"

[[methods]]
parent = "CachedSubjectBase"
name = "RetrieveFromCache"
sig = "void RetrieveFromCache()"
returns = "void"
file = "Subjects\\CachedSubjectBase.cs"

[[methods]]
parent = "CachedSubjectBase"
name = "DisposeCurrentData"
sig = "void DisposeCurrentData()"
returns = "void"
file = "Subjects\\CachedSubjectBase.cs"

[[methods]]
parent = "CachedSubjectBase"
name = "ConvertModelToCachedData"
sig = "TCacheable ConvertModelToCachedData(T data)"
returns = "TCacheable"
file = "Subjects\\CachedSubjectBase.cs"

[[methods]]
parent = "CachedSubjectBase"
name = "ConvertCachedDataToModel"
sig = "T ConvertCachedDataToModel(TCacheable cachedData)"
returns = "T"
file = "Subjects\\CachedSubjectBase.cs"

[[classes]]
name = "CollectionCachedSubject"
ns = "FEx.PersistentStorage.Rx.Subjects"
base = "CollectionCachedSubjectBase<T, TCacheable>"
file = "Subjects\\CollectionCachedSubject.cs"

[[ctors]]
parent = "CollectionCachedSubject"
sig = "CollectionCachedSubject(ICacheService cacheService, ClearCacheReason clearCacheReason)"
file = "Subjects\\CollectionCachedSubject.cs"

[[methods]]
parent = "CollectionCachedSubject"
name = "RetrieveFromCache"
sig = "void RetrieveFromCache()"
returns = "void"
file = "Subjects\\CollectionCachedSubject.cs"

[[classes]]
name = "CollectionCachedSubjectBase"
ns = "FEx.PersistentStorage.Rx.Subjects"
base = "CachedSubjectBase<IReadOnlyCollection<T>, T, TCacheable>"
file = "Subjects\\CollectionCachedSubjectBase.cs"

[[ctors]]
parent = "CollectionCachedSubjectBase"
sig = "CollectionCachedSubjectBase(ICacheService cacheService, ClearCacheReason clearCacheReason)"
file = "Subjects\\CollectionCachedSubjectBase.cs"

[[methods]]
parent = "CollectionCachedSubjectBase"
name = "OnNext"
sig = "void OnNext(IReadOnlyCollection<T> value)"
returns = "void"
file = "Subjects\\CollectionCachedSubjectBase.cs"

[[methods]]
parent = "CollectionCachedSubjectBase"
name = "DisposeCurrentData"
sig = "void DisposeCurrentData()"
returns = "void"
file = "Subjects\\CollectionCachedSubjectBase.cs"

[[classes]]
name = "EnhancedCollectionCachedSubject"
ns = "FEx.PersistentStorage.Rx.Subjects"
base = "CollectionCachedSubjectBase<T, TCacheable>"
file = "Subjects\\EnhancedCollectionCachedSubject.cs"

[[ctors]]
parent = "EnhancedCollectionCachedSubject"
sig = "EnhancedCollectionCachedSubject(ICacheService cacheService, ClearCacheReason clearCacheReason)"
file = "Subjects\\EnhancedCollectionCachedSubject.cs"

[[methods]]
parent = "EnhancedCollectionCachedSubject"
name = "GetEnhancement"
sig = "TEnhancement GetEnhancement(List<TCacheable> cachedData)"
returns = "TEnhancement"
file = "Subjects\\EnhancedCollectionCachedSubject.cs"

[[methods]]
parent = "EnhancedCollectionCachedSubject"
name = "ConvertCachedDataToModel"
sig = "T ConvertCachedDataToModel(TCacheable cachedData, TEnhancement enhancement)"
returns = "T"
file = "Subjects\\EnhancedCollectionCachedSubject.cs"

[[methods]]
parent = "EnhancedCollectionCachedSubject"
name = "RetrieveFromCache"
sig = "void RetrieveFromCache()"
returns = "void"
file = "Subjects\\EnhancedCollectionCachedSubject.cs"

[[classes]]
name = "SingleCachedSubject"
ns = "FEx.PersistentStorage.Rx.Subjects"
base = "CachedSubjectBase<T, T, TCacheable>"
file = "Subjects\\SingleCachedSubject.cs"

[[ctors]]
parent = "SingleCachedSubject"
sig = "SingleCachedSubject(ICacheService cacheService, ClearCacheReason clearCacheReason)"
file = "Subjects\\SingleCachedSubject.cs"

[[ctors]]
parent = "SingleCachedSubject"
sig = "SingleCachedSubject(ICacheService cacheService, ClearCacheReason clearCacheReason, T defaultValue)"
file = "Subjects\\SingleCachedSubject.cs"

[[methods]]
parent = "SingleCachedSubject"
name = "OnNext"
sig = "void OnNext(T value)"
returns = "void"
file = "Subjects\\SingleCachedSubject.cs"

[[methods]]
parent = "SingleCachedSubject"
name = "RetrieveFromCache"
sig = "void RetrieveFromCache()"
returns = "void"
file = "Subjects\\SingleCachedSubject.cs"

[[methods]]
parent = "SingleCachedSubject"
name = "DisposeCurrentData"
sig = "void DisposeCurrentData()"
returns = "void"
file = "Subjects\\SingleCachedSubject.cs"

