[project]
name = "FEx.PersistentStorage.Abstractions"
path = "src\\PersistentStorage.Abstractions"

[[classes]]
name = "CacheableItem"
ns = "FEx.PersistentStorage.Abstractions"
base = "ICacheableItem"
file = "CacheableItem.cs"

[[properties]]
parent = "CacheableItem"
name = "LocalStorageId"
sig = "ObjectId LocalStorageId { get; set; }"
returns = "ObjectId"
file = "CacheableItem.cs"

[[properties]]
parent = "CacheableItem"
name = "TimeStamp"
sig = "DateTime TimeStamp { get; set; }"
returns = "DateTime"
file = "CacheableItem.cs"

[[ctors]]
parent = "CacheableItem"
sig = "CacheableItem()"
file = "CacheableItem.cs"

[[interfaces]]
name = "ICacheableItem"
ns = "FEx.PersistentStorage.Abstractions"
file = "ICacheableItem.cs"

[[properties]]
parent = "ICacheableItem"
name = "LocalStorageId"
sig = "ObjectId LocalStorageId { get; }"
returns = "ObjectId"
file = "ICacheableItem.cs"

[[interfaces]]
name = "ICacheService"
ns = "FEx.PersistentStorage.Abstractions"
base = "IFileLocalStorageService"
file = "ICacheService.cs"

[[methods]]
parent = "ICacheService"
name = "Add"
sig = "BsonValue Add<T>(T item) where T : ICacheableItem"
returns = "BsonValue"
summary = "Caches object"
file = "ICacheService.cs"

[[methods]]
parent = "ICacheService"
name = "Add"
sig = "void Add<T>(IEnumerable<T> items) where T : ICacheableItem"
returns = "void"
summary = "Caches the range of objects"
file = "ICacheService.cs"

[[methods]]
parent = "ICacheService"
name = "Update"
sig = "bool Update<T>(T item) where T : ICacheableItem"
returns = "bool"
summary = "Updates an existing object. May remove the entire collection."
file = "ICacheService.cs"

[[methods]]
parent = "ICacheService"
name = "Upsert"
sig = "bool Upsert<T>(T item, Expression<Func<T, bool>> predicate) where T : ICacheableItem"
returns = "bool"
summary = "Insert or Update object based on _id key or predicate."
file = "ICacheService.cs"

[[methods]]
parent = "ICacheService"
name = "Upsert"
sig = "void Upsert<T>(IEnumerable<T> items, Expression<Func<T, bool>> predicate) where T : ICacheableItem"
returns = "void"
summary = "Insert or Update objects based on _id key or predicate."
file = "ICacheService.cs"

[[methods]]
parent = "ICacheService"
name = "Delete"
sig = "bool Delete<T>(ObjectId id) where T : ICacheableItem"
returns = "bool"
summary = "Removes cached object of specified type"
file = "ICacheService.cs"

[[methods]]
parent = "ICacheService"
name = "Delete"
sig = "bool Delete<T>(IEnumerable<T> items) where T : ICacheableItem"
returns = "bool"
summary = "Removes cached objects"
file = "ICacheService.cs"

[[methods]]
parent = "ICacheService"
name = "Delete"
sig = "bool Delete<T>(Expression<Func<T, bool>> predicate) where T : ICacheableItem"
returns = "bool"
summary = "Removes cached objects that meet criteria of the predicate"
file = "ICacheService.cs"

[[methods]]
parent = "ICacheService"
name = "FirstOrDefault"
sig = "T FirstOrDefault<T>(Expression<Func<T, bool>> predicate) where T : ICacheableItem"
returns = "T"
summary = "Tries to find an object in cache that meets the requirements of the predicate"
file = "ICacheService.cs"

[[methods]]
parent = "ICacheService"
name = "Get"
sig = "IReadOnlyCollection<T> Get<T>(Expression<Func<T, bool>> predicate) where T : ICacheableItem"
returns = "IReadOnlyCollection<T>"
summary = "The entire collection of cached objects of specified type matching predicate or all of them if predicate is null."
file = "ICacheService.cs"

[[methods]]
parent = "ICacheService"
name = "ReplaceWith"
sig = "void ReplaceWith<T>(IEnumerable<T> items) where T : ICacheableItem"
returns = "void"
summary = "Deletes all items in provided items collection and replaces it with that items"
file = "ICacheService.cs"

[[methods]]
parent = "ICacheService"
name = "ReplaceWith"
sig = "BsonValue ReplaceWith<T>(T item) where T : ICacheableItem"
returns = "BsonValue"
summary = "Deletes all items in provided item collection and replaces it with that single item"
file = "ICacheService.cs"

[[methods]]
parent = "ICacheService"
name = "ClearCache"
sig = "void ClearCache(ClearCacheReason clearCacheReason)"
returns = "void"
summary = "Calls the ClearCache method of inheritors of IClearCache for the selected Cached Type"
file = "ICacheService.cs"

[[interfaces]]
name = "IClearCache"
ns = "FEx.PersistentStorage.Abstractions"
file = "IClearCache.cs"

[[properties]]
parent = "IClearCache"
name = "ClearCacheReason"
sig = "ClearCacheReason ClearCacheReason { get; }"
returns = "ClearCacheReason"
file = "IClearCache.cs"

[[properties]]
parent = "IClearCache"
name = "ClearCachePriority"
sig = "ClearCachePriority ClearCachePriority { get; }"
returns = "ClearCachePriority"
file = "IClearCache.cs"

[[methods]]
parent = "IClearCache"
name = "ClearCache"
sig = "void ClearCache()"
returns = "void"
file = "IClearCache.cs"

[[interfaces]]
name = "IDatabaseFilePathResolver"
ns = "FEx.PersistentStorage.Abstractions"
file = "IDatabaseFilePathResolver.cs"

[[methods]]
parent = "IDatabaseFilePathResolver"
name = "GetDatabasesFolderPath"
sig = "string GetDatabasesFolderPath()"
returns = "string"
file = "IDatabaseFilePathResolver.cs"

[[interfaces]]
name = "IDatabaseProvider"
ns = "FEx.PersistentStorage.Abstractions"
file = "IDatabaseProvider.cs"

[[properties]]
parent = "IDatabaseProvider"
name = "Repository"
sig = "ILiteRepository Repository { get; }"
returns = "ILiteRepository"
file = "IDatabaseProvider.cs"

[[properties]]
parent = "IDatabaseProvider"
name = "DbLock"
sig = "ExtendedReaderWriterLockSlim DbLock { get; }"
returns = "ExtendedReaderWriterLockSlim"
file = "IDatabaseProvider.cs"

[[interfaces]]
name = "IFExCachedFile"
ns = "FEx.PersistentStorage.Abstractions"
base = "IDisposable"
file = "IFExCachedFile.cs"

[[properties]]
parent = "IFExCachedFile"
name = "Timestamp"
sig = "DateTime Timestamp { get; }"
returns = "DateTime"
file = "IFExCachedFile.cs"

[[properties]]
parent = "IFExCachedFile"
name = "IsExpired"
sig = "bool IsExpired { get; }"
returns = "bool"
file = "IFExCachedFile.cs"

[[properties]]
parent = "IFExCachedFile"
name = "Filename"
sig = "string Filename { get; }"
returns = "string"
file = "IFExCachedFile.cs"

[[properties]]
parent = "IFExCachedFile"
name = "IsDownloading"
sig = "bool IsDownloading { get; set; }"
returns = "bool"
file = "IFExCachedFile.cs"

[[properties]]
parent = "IFExCachedFile"
name = "Url"
sig = "Uri Url { get; }"
returns = "Uri"
file = "IFExCachedFile.cs"

[[properties]]
parent = "IFExCachedFile"
name = "Id"
sig = "string Id { get; }"
returns = "string"
file = "IFExCachedFile.cs"

[[methods]]
parent = "IFExCachedFile"
name = "UpdateData"
sig = "void UpdateData(IFExCachedFile data)"
returns = "void"
file = "IFExCachedFile.cs"

[[methods]]
parent = "IFExCachedFile"
name = "GetDataStream"
sig = "MemoryStream GetDataStream()"
returns = "MemoryStream"
file = "IFExCachedFile.cs"

[[methods]]
parent = "IFExCachedFile"
name = "GetDataStreamAsync"
sig = "Task<MemoryStream> GetDataStreamAsync(CancellationToken cancellationToken)"
returns = "Task<MemoryStream>"
file = "IFExCachedFile.cs"

[[interfaces]]
name = "IFExDownloadResult"
ns = "FEx.PersistentStorage.Abstractions"
base = "IDisposable"
file = "IFExDownloadResult.cs"

[[properties]]
parent = "IFExDownloadResult"
name = "Url"
sig = "Uri Url { get; }"
returns = "Uri"
file = "IFExDownloadResult.cs"

[[properties]]
parent = "IFExDownloadResult"
name = "FileName"
sig = "string FileName { get; }"
returns = "string"
file = "IFExDownloadResult.cs"

[[methods]]
parent = "IFExDownloadResult"
name = "UseDataStream"
sig = "void UseDataStream(Action<MemoryStream> streamAction)"
returns = "void"
file = "IFExDownloadResult.cs"

[[methods]]
parent = "IFExDownloadResult"
name = "UseDataStream"
sig = "T UseDataStream<T>(Func<MemoryStream, T> streamAction)"
returns = "T"
file = "IFExDownloadResult.cs"

[[interfaces]]
name = "IFExPersistentStorageContainer"
ns = "FEx.PersistentStorage.Abstractions"
base = "IContainer<IDatabaseProvider>, IContainer<ICacheService>, IContainer<IFileLocalStorageService>, IContainer<ILocalStorageService>"
file = "IFExPersistencyStorageContainer.cs"

[[interfaces]]
name = "IFileLocalStorageService"
ns = "FEx.PersistentStorage.Abstractions"
file = "IFileLocalStorageService.cs"

[[methods]]
parent = "IFileLocalStorageService"
name = "CacheFile"
sig = "IFExCachedFile CacheFile(IFExDownloadResult downloadResult)"
returns = "IFExCachedFile"
summary = "Cache file stream"
file = "IFileLocalStorageService.cs"

[[methods]]
parent = "IFileLocalStorageService"
name = "GetCachedFile"
sig = "IFExCachedFile GetCachedFile(Uri fileUrl)"
returns = "IFExCachedFile"
summary = "Find cached file for provided download URL"
file = "IFileLocalStorageService.cs"

[[methods]]
parent = "IFileLocalStorageService"
name = "UpdateFile"
sig = "void UpdateFile(IFExCachedFile cachedFile)"
returns = "void"
summary = "Overwrite cached file with new value"
file = "IFileLocalStorageService.cs"

[[methods]]
parent = "IFileLocalStorageService"
name = "DeleteExpiredFiles"
sig = "void DeleteExpiredFiles()"
returns = "void"
summary = "Delete all outdated files from cache"
file = "IFileLocalStorageService.cs"

[[interfaces]]
name = "ILocalStorageService"
ns = "FEx.PersistentStorage.Abstractions"
base = "IFileLocalStorageService"
file = "ILocalStorageService.cs"

[[methods]]
parent = "ILocalStorageService"
name = "GetAll"
sig = "IReadOnlyList<T> GetAll<T>(Expression<Func<T, bool>> predicate) where T : ICacheableItem"
returns = "IReadOnlyList<T>"
summary = "Returns all objects, or only those matching predicate, inside collection ordered by _id index."
file = "ILocalStorageService.cs"

[[methods]]
parent = "ILocalStorageService"
name = "FirstOrDefault"
sig = "T FirstOrDefault<T>(Expression<Func<T, bool>> predicate) where T : ICacheableItem"
returns = "T"
summary = "Returns first object of collection or null if there are no results of query"
file = "ILocalStorageService.cs"

[[methods]]
parent = "ILocalStorageService"
name = "Insert"
sig = "BsonValue Insert<T>(T item) where T : ICacheableItem"
returns = "BsonValue"
summary = "Insert a new object into collection."
file = "ILocalStorageService.cs"

[[methods]]
parent = "ILocalStorageService"
name = "Insert"
sig = "void Insert<T>(IEnumerable<T> items) where T : ICacheableItem"
returns = "void"
summary = "Insert an array of new objects into collection."
file = "ILocalStorageService.cs"

[[methods]]
parent = "ILocalStorageService"
name = "Update"
sig = "bool Update<T>(T item) where T : ICacheableItem"
returns = "bool"
summary = "Update object into collection."
file = "ILocalStorageService.cs"

[[methods]]
parent = "ILocalStorageService"
name = "Upsert"
sig = "bool Upsert<T>(T item, Expression<Func<T, bool>> predicate) where T : ICacheableItem"
returns = "bool"
summary = "Insert or Update object based on _id key or predicate."
file = "ILocalStorageService.cs"

[[methods]]
parent = "ILocalStorageService"
name = "Upsert"
sig = "void Upsert<T>(IEnumerable<T> items, Expression<Func<T, bool>> predicate) where T : ICacheableItem"
returns = "void"
summary = "Insert or Update objects based on _id key or predicate."
file = "ILocalStorageService.cs"

[[methods]]
parent = "ILocalStorageService"
name = "Delete"
sig = "bool Delete<T>(ObjectId id) where T : ICacheableItem"
returns = "bool"
summary = "Delete entity based on _id key"
file = "ILocalStorageService.cs"

[[methods]]
parent = "ILocalStorageService"
name = "Delete"
sig = "bool Delete<T>(IEnumerable<T> items) where T : ICacheableItem"
returns = "bool"
summary = "Deletes entities based on their _id key"
file = "ILocalStorageService.cs"

[[methods]]
parent = "ILocalStorageService"
name = "DeleteAll"
sig = "bool DeleteAll<T>(Expression<Func<T, bool>> predicate) where T : ICacheableItem"
returns = "bool"
summary = "Delete entity based on predicate filter expression"
file = "ILocalStorageService.cs"

[[methods]]
parent = "ILocalStorageService"
name = "ReplaceWith"
sig = "void ReplaceWith<T>(IEnumerable<T> items) where T : ICacheableItem"
returns = "void"
summary = "Deletes all items in provided items collection and replaces it with that items"
file = "ILocalStorageService.cs"

[[methods]]
parent = "ILocalStorageService"
name = "ReplaceWith"
sig = "BsonValue ReplaceWith<T>(T item) where T : ICacheableItem"
returns = "BsonValue"
summary = "Deletes all items in provided item collection and replaces it with that single item"
file = "ILocalStorageService.cs"

[[classes]]
name = "CacheServiceConfiguration"
ns = "FEx.PersistentStorage.Abstractions.Configuration"
file = "Configuration\\CacheServiceConfiguration.cs"
static = true

[[properties]]
parent = "CacheServiceConfiguration"
name = "ExpirationTimeSpan"
sig = "static TimeSpan ExpirationTimeSpan { get; set; }"
returns = "TimeSpan"
file = "Configuration\\CacheServiceConfiguration.cs"
static = true

[[enums]]
name = "ClearCachePriority"
ns = "FEx.PersistentStorage.Abstractions.Enums"
file = "Enums\\ClearCachePriority.cs"

[[enums]]
name = "ClearCacheReason"
ns = "FEx.PersistentStorage.Abstractions.Enums"
file = "Enums\\ClearCacheReason.cs"

[[classes]]
name = "CachedFileExtensions"
ns = "FEx.PersistentStorage.Abstractions.Extensions"
file = "Extensions\\CachedFileExtensions.cs"
static = true

[[extensions]]
name = "IsExpired"
returns = "bool"
sig = "bool IsExpired(this LiteFileInfo<string> file)"
file = "Extensions\\CachedFileExtensions.cs"

[[methods]]
parent = "CachedFileExtensions"
name = "IsExpired"
sig = "static bool IsExpired(DateTime timestamp)"
returns = "bool"
file = "Extensions\\CachedFileExtensions.cs"
static = true

[[methods]]
parent = "CachedFileExtensions"
name = "GetFileId"
sig = "static string GetFileId(Uri fileUrl)"
returns = "string"
file = "Extensions\\CachedFileExtensions.cs"
static = true

[[methods]]
parent = "CachedFileExtensions"
name = "GetIsExpiredPredicate"
sig = "static Expression<Func<LiteFileInfo<string>, bool>> GetIsExpiredPredicate()"
returns = "Expression<Func<LiteFileInfo<string>, bool>>"
file = "Extensions\\CachedFileExtensions.cs"
static = true

[[classes]]
name = "CacheServiceExtensions"
ns = "FEx.PersistentStorage.Abstractions.Extensions"
file = "Extensions\\CacheServiceExtensions.cs"
static = true

[[extensions]]
name = "Upsert"
returns = "bool"
sig = "bool Upsert<T>(this ICacheService service, T item)"
file = "Extensions\\CacheServiceExtensions.cs"

[[extensions]]
name = "Upsert"
returns = "void"
sig = "void Upsert<T>(this ICacheService service, IEnumerable<T> items)"
file = "Extensions\\CacheServiceExtensions.cs"

[[extensions]]
name = "Delete"
returns = "bool"
sig = "bool Delete<T>(this ICacheService service)"
file = "Extensions\\CacheServiceExtensions.cs"

[[extensions]]
name = "FirstOrDefault"
returns = "T"
sig = "T FirstOrDefault<T>(this ICacheService service)"
file = "Extensions\\CacheServiceExtensions.cs"

[[extensions]]
name = "Get"
returns = "IReadOnlyCollection<T>"
sig = "IReadOnlyCollection<T> Get<T>(this ICacheService service)"
file = "Extensions\\CacheServiceExtensions.cs"

[[classes]]
name = "ClearCacheReasonExtensions"
ns = "FEx.PersistentStorage.Abstractions.Extensions"
file = "Extensions\\ClearCacheReasonExtensions.cs"
static = true

[[extensions]]
name = "HasFlagFast"
returns = "bool"
sig = "bool HasFlagFast(this ClearCacheReason value, ClearCacheReason flag)"
file = "Extensions\\ClearCacheReasonExtensions.cs"

[[classes]]
name = "LocalStorageServiceExtensions"
ns = "FEx.PersistentStorage.Abstractions.Extensions"
file = "Extensions\\LocalStorageServiceExtensions.cs"
static = true

[[extensions]]
name = "GetAll"
returns = "IReadOnlyList<T>"
sig = "IReadOnlyList<T> GetAll<T>(this ILocalStorageService service)"
file = "Extensions\\LocalStorageServiceExtensions.cs"

[[extensions]]
name = "FirstOrDefault"
returns = "T"
sig = "T FirstOrDefault<T>(this ILocalStorageService service)"
file = "Extensions\\LocalStorageServiceExtensions.cs"

[[extensions]]
name = "Upsert"
returns = "bool"
sig = "bool Upsert<T>(this ILocalStorageService service, T item)"
file = "Extensions\\LocalStorageServiceExtensions.cs"

[[extensions]]
name = "Upsert"
returns = "void"
sig = "void Upsert<T>(this ILocalStorageService service, IEnumerable<T> items)"
file = "Extensions\\LocalStorageServiceExtensions.cs"

[[extensions]]
name = "DeleteAll"
returns = "bool"
sig = "bool DeleteAll<T>(this ILocalStorageService service)"
file = "Extensions\\LocalStorageServiceExtensions.cs"

[[classes]]
name = "FExCachedFile"
ns = "FEx.PersistentStorage.Abstractions.Models"
base = "NotifyPropertyChanged, IFExCachedFile, IAsyncDisposable"
file = "Models\\FExCachedFile.cs"

[[properties]]
parent = "FExCachedFile"
name = "Filename"
sig = "string Filename { get; }"
returns = "string"
file = "Models\\FExCachedFile.cs"

[[properties]]
parent = "FExCachedFile"
name = "Timestamp"
sig = "DateTime Timestamp { get; }"
returns = "DateTime"
file = "Models\\FExCachedFile.cs"

[[properties]]
parent = "FExCachedFile"
name = "IsExpired"
sig = "bool IsExpired { get; }"
returns = "bool"
file = "Models\\FExCachedFile.cs"

[[properties]]
parent = "FExCachedFile"
name = "Url"
sig = "Uri Url { get; }"
returns = "Uri"
file = "Models\\FExCachedFile.cs"

[[properties]]
parent = "FExCachedFile"
name = "Id"
sig = "string Id { get; }"
returns = "string"
file = "Models\\FExCachedFile.cs"

[[properties]]
parent = "FExCachedFile"
name = "IsDownloading"
sig = "bool IsDownloading { get; set; }"
returns = "bool"
file = "Models\\FExCachedFile.cs"

[[ctors]]
parent = "FExCachedFile"
sig = "FExCachedFile(LiteFileInfo<string> file)"
file = "Models\\FExCachedFile.cs"

[[ctors]]
parent = "FExCachedFile"
sig = "FExCachedFile(FileInfo file, Uri url)"
file = "Models\\FExCachedFile.cs"

[[ctors]]
parent = "FExCachedFile"
sig = "FExCachedFile(IFExDownloadResult downloadResult)"
file = "Models\\FExCachedFile.cs"

[[methods]]
parent = "FExCachedFile"
name = "UpdateData"
sig = "void UpdateData(IFExCachedFile data)"
returns = "void"
file = "Models\\FExCachedFile.cs"

[[methods]]
parent = "FExCachedFile"
name = "GetDataStream"
sig = "MemoryStream GetDataStream()"
returns = "MemoryStream"
file = "Models\\FExCachedFile.cs"

[[methods]]
parent = "FExCachedFile"
name = "GetDataStreamAsync"
sig = "Task<MemoryStream> GetDataStreamAsync(CancellationToken cancellationToken)"
returns = "Task<MemoryStream>"
file = "Models\\FExCachedFile.cs"

[[methods]]
parent = "FExCachedFile"
name = "Dispose"
sig = "void Dispose(bool disposing)"
returns = "void"
file = "Models\\FExCachedFile.cs"

[[methods]]
parent = "FExCachedFile"
name = "DisposeAsync"
sig = "ValueTask DisposeAsync(bool disposing)"
returns = "ValueTask"
file = "Models\\FExCachedFile.cs"

[[methods]]
parent = "FExCachedFile"
name = "Dispose"
sig = "void Dispose()"
returns = "void"
file = "Models\\FExCachedFile.cs"

[[methods]]
parent = "FExCachedFile"
name = "DisposeAsync"
sig = "ValueTask DisposeAsync()"
returns = "ValueTask"
file = "Models\\FExCachedFile.cs"

