[project]
name = "FEx.RESXx"
path = "src\\FEx.RESXx"

[[classes]]
name = "ResxManager"
ns = "FEx.RESXx"
base = "IResxManager"
file = "ResxManager.cs"

[[methods]]
parent = "ResxManager"
name = "UpdateResourceFile"
sig = "void UpdateResourceFile(List<KeyValuePair<string, string>> data, string path)"
returns = "void"
file = "ResxManager.cs"

[[methods]]
parent = "ResxManager"
name = "GetResourcesEntries"
sig = "Dictionary<string, string> GetResourcesEntries(string path)"
returns = "Dictionary<string, string>"
file = "ResxManager.cs"

[[methods]]
parent = "ResxManager"
name = "Resgen"
sig = "string[] Resgen(string resx, string resxDesigner, string fileName, string projectNamespace)"
returns = "string[]"
summary = "Resgens the specified file."
file = "ResxManager.cs"

