[project]
name = "FEx.Sqlx"
path = "src\\Sqlx"

[[classes]]
name = "SqlDbHelper"
ns = "FEx.Sqlx"
base = "AsyncInitializable, ISqlDbHelper"
file = "SqlDbHelper.cs"

[[properties]]
parent = "SqlDbHelper"
name = "SQLInstanceInfo"
sig = "SQLInstanceInfo SQLInstanceInfo { get; }"
returns = "SQLInstanceInfo"
file = "SqlDbHelper.cs"

[[properties]]
parent = "SqlDbHelper"
name = "SQLInstance"
sig = "string SQLInstance { get; }"
returns = "string"
file = "SqlDbHelper.cs"

[[ctors]]
parent = "SqlDbHelper"
sig = "SqlDbHelper()"
file = "SqlDbHelper.cs"

[[methods]]
parent = "SqlDbHelper"
name = "GetSqlInstancesAsync"
sig = "static Task<IList<SQLInstanceInfo>> GetSqlInstancesAsync()"
returns = "Task<IList<SQLInstanceInfo>>"
file = "SqlDbHelper.cs"
static = true

[[methods]]
parent = "SqlDbHelper"
name = "OnInitializeAsync"
sig = "Task OnInitializeAsync()"
returns = "Task"
file = "SqlDbHelper.cs"

[[classes]]
name = "SQLInstanceInfo"
ns = "FEx.Sqlx"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "SQLInstance"
sig = "string SQLInstance { get; }"
returns = "string"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "BuildClrVersion"
sig = "Version BuildClrVersion { get; set; }"
returns = "Version"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "Collation"
sig = "string Collation { get; set; }"
returns = "string"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "CollationID"
sig = "int? CollationID { get; set; }"
returns = "int?"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "ComparisonStyle"
sig = "int? ComparisonStyle { get; set; }"
returns = "int?"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "ComputerNamePhysicalNetBIOS"
sig = "string ComputerNamePhysicalNetBIOS { get; set; }"
returns = "string"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "Edition"
sig = "string Edition { get; set; }"
returns = "string"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "EditionID"
sig = "string EditionID { get; set; }"
returns = "string"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "EngineEdition"
sig = "string EngineEdition { get; set; }"
returns = "string"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "FilestreamConfiguredLevel"
sig = "FileStreamEffectiveLevel? FilestreamConfiguredLevel { get; set; }"
returns = "FileStreamEffectiveLevel?"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "FilestreamEffectiveLevel"
sig = "FileStreamEffectiveLevel? FilestreamEffectiveLevel { get; set; }"
returns = "FileStreamEffectiveLevel?"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "FilestreamShareName"
sig = "string FilestreamShareName { get; set; }"
returns = "string"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "HadrManagerStatus"
sig = "HadrManagerStatus? HadrManagerStatus { get; set; }"
returns = "HadrManagerStatus?"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "InstanceDefaultBackupPath"
sig = "string InstanceDefaultBackupPath { get; set; }"
returns = "string"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "InstanceDefaultDataPath"
sig = "string InstanceDefaultDataPath { get; set; }"
returns = "string"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "InstanceDefaultLogPath"
sig = "string InstanceDefaultLogPath { get; set; }"
returns = "string"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "InstanceName"
sig = "string InstanceName { get; set; }"
returns = "string"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "IsAdvancedAnalyticsInstalled"
sig = "bool? IsAdvancedAnalyticsInstalled { get; set; }"
returns = "bool?"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "IsBigDataCluster"
sig = "bool? IsBigDataCluster { get; set; }"
returns = "bool?"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "IsClustered"
sig = "bool? IsClustered { get; set; }"
returns = "bool?"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "IsFullTextInstalled"
sig = "bool? IsFullTextInstalled { get; set; }"
returns = "bool?"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "IsHadrEnabled"
sig = "bool? IsHadrEnabled { get; set; }"
returns = "bool?"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "IsIntegratedSecurityOnly"
sig = "bool? IsIntegratedSecurityOnly { get; set; }"
returns = "bool?"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "IsLocalDB"
sig = "bool IsLocalDB { get; set; }"
returns = "bool"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "IsPolyBaseInstalled"
sig = "bool? IsPolyBaseInstalled { get; set; }"
returns = "bool?"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "IsSingleUser"
sig = "bool? IsSingleUser { get; set; }"
returns = "bool?"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "IsTempDbMetadataMemoryOptimized"
sig = "bool? IsTempDbMetadataMemoryOptimized { get; set; }"
returns = "bool?"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "IsXTPSupported"
sig = "bool? IsXTPSupported { get; set; }"
returns = "bool?"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "LCID"
sig = "int? LCID { get; set; }"
returns = "int?"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "LicenseType"
sig = "string LicenseType { get; set; }"
returns = "string"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "MachineName"
sig = "string MachineName { get; set; }"
returns = "string"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "NumLicenses"
sig = "string NumLicenses { get; set; }"
returns = "string"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "ProcessID"
sig = "int? ProcessID { get; set; }"
returns = "int?"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "ProductBuild"
sig = "string ProductBuild { get; set; }"
returns = "string"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "ProductBuildType"
sig = "string ProductBuildType { get; set; }"
returns = "string"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "ProductLevel"
sig = "string ProductLevel { get; set; }"
returns = "string"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "ProductMajorVersion"
sig = "string ProductMajorVersion { get; set; }"
returns = "string"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "ProductMinorVersion"
sig = "string ProductMinorVersion { get; set; }"
returns = "string"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "ProductUpdateLevel"
sig = "string ProductUpdateLevel { get; set; }"
returns = "string"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "ProductUpdateReference"
sig = "string ProductUpdateReference { get; set; }"
returns = "string"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "ProductVersion"
sig = "Version ProductVersion { get; set; }"
returns = "Version"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "ResourceLastUpdateDateTime"
sig = "DateTime? ResourceLastUpdateDateTime { get; set; }"
returns = "DateTime?"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "ResourceVersion"
sig = "Version ResourceVersion { get; set; }"
returns = "Version"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "ServerName"
sig = "string ServerName { get; set; }"
returns = "string"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "SqlCharSet"
sig = "short? SqlCharSet { get; set; }"
returns = "short?"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "SqlCharSetName"
sig = "string SqlCharSetName { get; set; }"
returns = "string"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "SqlSortOrder"
sig = "short? SqlSortOrder { get; set; }"
returns = "short?"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "SqlSortOrderName"
sig = "string SqlSortOrderName { get; set; }"
returns = "string"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "LoginMode"
sig = "ServerLoginMode LoginMode { get; }"
returns = "ServerLoginMode"
file = "SQLInstanceInfo.cs"

[[properties]]
parent = "SQLInstanceInfo"
name = "Server"
sig = "Server Server { get; set; }"
returns = "Server"
file = "SQLInstanceInfo.cs"

[[ctors]]
parent = "SQLInstanceInfo"
sig = "SQLInstanceInfo(string instanceName)"
file = "SQLInstanceInfo.cs"

[[methods]]
parent = "SQLInstanceInfo"
name = "LoadInfoAsync"
sig = "Task<bool> LoadInfoAsync()"
returns = "Task<bool>"
file = "SQLInstanceInfo.cs"

[[methods]]
parent = "SQLInstanceInfo"
name = "LoadInfo"
sig = "bool LoadInfo()"
returns = "bool"
file = "SQLInstanceInfo.cs"

[[enums]]
name = "ServerEditionID"
ns = "FEx.Sqlx.Enums"
file = "Enums\\ServerEditionID.cs"

[[enums]]
name = "ServerEngineEdition"
ns = "FEx.Sqlx.Enums"
file = "Enums\\ServerEngineEdition.cs"

[[enums]]
name = "ServerProp"
ns = "FEx.Sqlx.Enums"
file = "Enums\\ServerProp.cs"

[[classes]]
name = "SqlConnectionExtensions"
ns = "FEx.Sqlx.Extensions"
file = "Extensions\\SqlConnectionExtensions.cs"
static = true

[[properties]]
parent = "SqlConnectionExtensions"
name = "ServerProps"
sig = "static IMap<string, ServerProp> ServerProps { get; }"
returns = "IMap<string, ServerProp>"
file = "Extensions\\SqlConnectionExtensions.cs"
static = true

[[properties]]
parent = "SqlConnectionExtensions"
name = "ServerEditionIDs"
sig = "static IMap<long, string> ServerEditionIDs { get; }"
returns = "IMap<long, string>"
file = "Extensions\\SqlConnectionExtensions.cs"
static = true

[[properties]]
parent = "SqlConnectionExtensions"
name = "ServerEngineEditions"
sig = "static IMap<int, string> ServerEngineEditions { get; }"
returns = "IMap<int, string>"
file = "Extensions\\SqlConnectionExtensions.cs"
static = true

[[properties]]
parent = "SqlConnectionExtensions"
name = "PropsSQL"
sig = "static string PropsSQL { get; }"
returns = "string"
file = "Extensions\\SqlConnectionExtensions.cs"
static = true

[[extensions]]
name = "RunSqlAsync"
returns = "Task<IDictionary<string, object>[]>"
sig = "Task<IDictionary<string, object>[]> RunSqlAsync(this MsSqlConnection connection, string sql)"
file = "Extensions\\SqlConnectionExtensions.cs"

[[extensions]]
name = "RunSqlAsync"
returns = "Task<IDictionary<string, object>[]>"
sig = "Task<IDictionary<string, object>[]> RunSqlAsync(this SqlConnection connection, string sql)"
file = "Extensions\\SqlConnectionExtensions.cs"

[[extensions]]
name = "RunSql"
returns = "IDictionary<string, object>[]"
sig = "IDictionary<string, object>[] RunSql(this MsSqlConnection connection, string sql)"
file = "Extensions\\SqlConnectionExtensions.cs"

[[extensions]]
name = "RunSql"
returns = "IDictionary<string, object>[]"
sig = "IDictionary<string, object>[] RunSql(this SqlConnection connection, string sql)"
file = "Extensions\\SqlConnectionExtensions.cs"

[[extensions]]
name = "LoadDatabasesAsync"
returns = "Task<IList<string>>"
sig = "Task<IList<string>> LoadDatabasesAsync(this SqlConnection connection)"
file = "Extensions\\SqlConnectionExtensions.cs"

[[extensions]]
name = "LoadTablesAsync"
returns = "Task<Dictionary<string, long>>"
sig = "Task<Dictionary<string, long>> LoadTablesAsync(this SqlConnection connection)"
file = "Extensions\\SqlConnectionExtensions.cs"

[[extensions]]
name = "LoadColumnsAsync"
returns = "Task<(long tableId, string[] columnNames)>"
sig = "Task<(long tableId, string[] columnNames)> LoadColumnsAsync( this SqlConnection connection, long tableId, IProgress<bool> prg = null)"
file = "Extensions\\SqlConnectionExtensions.cs"

