[project]
name = "FEx.Telemetry.Sentry"
path = "src\\FEx.Telemetry.Sentry"

[[classes]]
name = "FExSentryConfig"
ns = "FEx.Telemetry.Sentry"
base = "FExTelemetryConfigBase, ISentryConfig"
file = "FExSentryConfig.cs"

[[properties]]
parent = "FExSentryConfig"
name = "SentryDsn"
sig = "string SentryDsn { get; }"
returns = "string"
file = "FExSentryConfig.cs"

[[properties]]
parent = "FExSentryConfig"
name = "AttachScreenshot"
sig = "bool AttachScreenshot { get; }"
returns = "bool"
file = "FExSentryConfig.cs"

[[properties]]
parent = "FExSentryConfig"
name = "EnvironmentId"
sig = "string EnvironmentId { get; }"
returns = "string"
file = "FExSentryConfig.cs"

[[properties]]
parent = "FExSentryConfig"
name = "SentryEnvironment"
sig = "string SentryEnvironment { get; }"
returns = "string"
file = "FExSentryConfig.cs"

[[ctors]]
parent = "FExSentryConfig"
sig = "FExSentryConfig(string dsn, string envVarOverride = \"SENTRY_DSN\")"
file = "FExSentryConfig.cs"

[[methods]]
parent = "FExSentryConfig"
name = "OnAccessTokenChanged"
sig = "void OnAccessTokenChanged(string accessToken)"
returns = "void"
file = "FExSentryConfig.cs"

[[classes]]
name = "FExSentryModule"
ns = "FEx.Telemetry.Sentry"
base = "FExTelemetryModule"
file = "FExSentryModule.cs"

[[methods]]
parent = "FExSentryModule"
name = "AddServices"
sig = "static void AddServices(ISentryModule container, IServiceCollection services)"
returns = "void"
file = "FExSentryModule.cs"
static = true

[[classes]]
name = "FExSentryx"
ns = "FEx.Telemetry.Sentry"
base = "InitializeModule<ISentryModule, IServiceCollection>"
file = "FExSentryx.cs"

[[properties]]
parent = "FExSentryx"
name = "SentrySrv"
sig = "static ISentryService SentrySrv { get; }"
returns = "ISentryService"
file = "FExSentryx.cs"
static = true

[[ctors]]
parent = "FExSentryx"
sig = "FExSentryx(ISentryService sentrySrv)"
file = "FExSentryx.cs"

[[methods]]
parent = "FExSentryx"
name = "RegisterServices"
sig = "void RegisterServices(ISentryModule container, IServiceCollection services)"
returns = "void"
file = "FExSentryx.cs"

[[classes]]
name = "SentrySinkConfigurator"
ns = "FEx.Telemetry.Sentry"
base = "SentrySinkConfiguratorBase"
file = "SentrySinkConfigurator.cs"

[[ctors]]
parent = "SentrySinkConfigurator"
sig = "SentrySinkConfigurator(ISentryConfig sentryConfig, ILoggingConfiguration loggingConfiguration, IAppVersionProvider appVersionProvider)"
file = "SentrySinkConfigurator.cs"

[[methods]]
parent = "SentrySinkConfigurator"
name = "ConfigureSink"
sig = "LoggerConfiguration ConfigureSink(LoggerSinkConfiguration writeTo)"
returns = "LoggerConfiguration"
file = "SentrySinkConfigurator.cs"

[[classes]]
name = "SentryConfigBase"
ns = "FEx.Telemetry.Sentry.Configuration"
base = "ISentryConfig"
file = "Configuration\\SentryConfigBase.cs"

[[properties]]
parent = "SentryConfigBase"
name = "SentryDsn"
sig = "string SentryDsn { get; }"
returns = "string"
file = "Configuration\\SentryConfigBase.cs"

[[properties]]
parent = "SentryConfigBase"
name = "AttachScreenshot"
sig = "bool AttachScreenshot { get; }"
returns = "bool"
file = "Configuration\\SentryConfigBase.cs"

[[properties]]
parent = "SentryConfigBase"
name = "EnvironmentId"
sig = "string EnvironmentId { get; }"
returns = "string"
file = "Configuration\\SentryConfigBase.cs"

[[classes]]
name = "SentryServiceExtensions"
ns = "FEx.Telemetry.Sentry.Extensions"
file = "Extensions\\SentryServiceExtensions.cs"
static = true

[[extensions]]
name = "InitializeFromConfig"
returns = "void"
sig = "void InitializeFromConfig(this ISentryService service, FExSentryConfig config, Assembly appAssembly)"
file = "Extensions\\SentryServiceExtensions.cs"

[[classes]]
name = "SentryService"
ns = "FEx.Telemetry.Sentry.Services"
base = "ISentryService, IDisposable"
file = "Services\\SentryService.cs"

[[properties]]
parent = "SentryService"
name = "IsInitialized"
sig = "bool IsInitialized { get; }"
returns = "bool"
file = "Services\\SentryService.cs"

[[methods]]
parent = "SentryService"
name = "Initialize"
sig = "void Initialize(string dsn, string environment, string release)"
returns = "void"
file = "Services\\SentryService.cs"

[[methods]]
parent = "SentryService"
name = "CaptureException"
sig = "void CaptureException(Exception exception)"
returns = "void"
file = "Services\\SentryService.cs"

[[methods]]
parent = "SentryService"
name = "FlushAsync"
sig = "Task FlushAsync(TimeSpan? timeout = null)"
returns = "Task"
file = "Services\\SentryService.cs"

[[methods]]
parent = "SentryService"
name = "Dispose"
sig = "void Dispose()"
returns = "void"
file = "Services\\SentryService.cs"

[[interfaces]]
name = "ISentryModule"
ns = "FEx.Telemetry.Sentry.Abstractions.Interfaces"
base = "IFExTelemetryModule, IContainer<ISentryService>, IContainer<FExSentryx>"
file = "Abstractions\\Interfaces\\ISentryModule.cs"

[[interfaces]]
name = "ISentryService"
ns = "FEx.Telemetry.Sentry.Abstractions.Interfaces"
file = "Abstractions\\Interfaces\\ISentryService.cs"

[[properties]]
parent = "ISentryService"
name = "IsInitialized"
sig = "bool IsInitialized { get; }"
returns = "bool"
file = "Abstractions\\Interfaces\\ISentryService.cs"

[[methods]]
parent = "ISentryService"
name = "Initialize"
sig = "void Initialize(string dsn, string environment, string release)"
returns = "void"
file = "Abstractions\\Interfaces\\ISentryService.cs"

[[methods]]
parent = "ISentryService"
name = "CaptureException"
sig = "void CaptureException(Exception exception)"
returns = "void"
file = "Abstractions\\Interfaces\\ISentryService.cs"

[[methods]]
parent = "ISentryService"
name = "FlushAsync"
sig = "Task FlushAsync(TimeSpan? timeout = null)"
returns = "Task"
file = "Abstractions\\Interfaces\\ISentryService.cs"

