[project]
name = "FEx.Telemetry.Sentry.Web"
path = "src\\FEx.Telemetry.Sentry.Web"

[[classes]]
name = "FExSentryWebExtensions"
ns = "FEx.Telemetry.Sentry.Web"
file = "FExSentryWebExtensions.cs"
static = true

[[extensions]]
name = "AddFExSentry"
returns = "WebApplicationBuilder"
sig = "WebApplicationBuilder AddFExSentry(this WebApplicationBuilder builder, string envVarOverride = \"SENTRY_DSN\")"
file = "FExSentryWebExtensions.cs"

