[project]
name = "FEx.Telemetry.Sentry"
path = "src\\FEx.Telemetry.Sentry"

[[classes]]
name = "FExSentryConfig"
ns = "FEx.Telemetry.Sentry"
base = "FExTelemetryConfigBase, ISentryConfig"
file = "FExSentryConfig.cs"

[[classes]]
name = "FExSentryModule"
ns = "FEx.Telemetry.Sentry"
base = "FExTelemetryModule"
file = "FExSentryModule.cs"

[[classes]]
name = "FExSentryx"
ns = "FEx.Telemetry.Sentry"
base = "InitializeModule<ISentryModule, IServiceCollection>"
file = "FExSentryx.cs"

[[classes]]
name = "SentrySinkConfigurator"
ns = "FEx.Telemetry.Sentry"
base = "SentrySinkConfiguratorBase"
file = "SentrySinkConfigurator.cs"

[[interfaces]]
name = "ISentryModule"
ns = "FEx.Telemetry.Sentry.Abstractions.Interfaces"
file = "Abstractions\\Interfaces\\ISentryModule.cs"

[[interfaces]]
name = "ISentryService"
ns = "FEx.Telemetry.Sentry.Abstractions.Interfaces"
file = "Abstractions\\Interfaces\\ISentryService.cs"

[[classes]]
name = "SentryConfigBase"
ns = "FEx.Telemetry.Sentry.Configuration"
base = "ISentryConfig"
file = "Configuration\\SentryConfigBase.cs"

[[classes]]
name = "SentryServiceExtensions"
ns = "FEx.Telemetry.Sentry.Extensions"
file = "Extensions\\SentryServiceExtensions.cs"
static = true

[[extensions]]
name = "InitializeFromConfig"
sig = "void InitializeFromConfig(this ISentryService service, FExSentryConfig config, Assembly appAssembly)"
returns = "void"
file = "Extensions\\SentryServiceExtensions.cs"

[[classes]]
name = "SentryService"
ns = "FEx.Telemetry.Sentry.Services"
base = "ISentryService, IDisposable"
file = "Services\\SentryService.cs"

