[project]
name = "FEx.WebScraping"
path = "src\\FEx.WebScraping"

[[classes]]
name = "HtmlWebHelper"
ns = "FEx.WebScraping"
base = "IWebScraper"
file = "HtmlWebHelper.cs"

[[methods]]
parent = "HtmlWebHelper"
name = "LoadHtmlDocumentAsync"
sig = "Task<HtmlDocument> LoadHtmlDocumentAsync(Uri pageLink, Action<HtmlWeb> configWeb, Encoding encoding, NetworkCredential credential, CancellationToken cancellationToken)"
returns = "Task<HtmlDocument>"
file = "HtmlWebHelper.cs"

[[methods]]
parent = "HtmlWebHelper"
name = "LoadAsync"
sig = "Task<T> LoadAsync<T>(Uri pageLink, Func<Uri, HtmlWeb, HtmlDocument, T> action, Action<HtmlWeb> configWeb, Encoding encoding, NetworkCredential credential, CancellationToken cancellationToken)"
returns = "Task<T>"
file = "HtmlWebHelper.cs"

[[methods]]
parent = "HtmlWebHelper"
name = "Load"
sig = "(HtmlWeb web, Task<HtmlDocument> docTask) Load(Uri pageLink, Action<HtmlWeb> configWeb, Encoding encoding, NetworkCredential credential, CancellationToken cancellationToken)"
returns = "(HtmlWeb web, Task<HtmlDocument> docTask)"
file = "HtmlWebHelper.cs"

[[methods]]
parent = "HtmlWebHelper"
name = "LoadHtmlDocumentAsync"
sig = "Task<HtmlDocument> LoadHtmlDocumentAsync(HtmlWeb web, Uri pageLink, Encoding encoding, NetworkCredential credential, CancellationToken cancellationToken)"
returns = "Task<HtmlDocument>"
file = "HtmlWebHelper.cs"

[[classes]]
name = "XPathBuilderBase"
ns = "FEx.WebScraping"
file = "XPathBuilderBase.cs"

[[properties]]
parent = "XPathBuilderBase"
name = "SB"
sig = "StringBuilder SB { get; }"
returns = "StringBuilder"
file = "XPathBuilderBase.cs"

[[ctors]]
parent = "XPathBuilderBase"
sig = "XPathBuilderBase()"
file = "XPathBuilderBase.cs"

[[ctors]]
parent = "XPathBuilderBase"
sig = "XPathBuilderBase(HtmlNode node)"
file = "XPathBuilderBase.cs"

[[methods]]
parent = "XPathBuilderBase"
name = "ToString"
sig = "string ToString()"
returns = "string"
file = "XPathBuilderBase.cs"

[[methods]]
parent = "XPathBuilderBase"
name = "This"
sig = "T This()"
returns = "T"
file = "XPathBuilderBase.cs"

[[methods]]
parent = "XPathBuilderBase"
name = "AllChildElements"
sig = "T AllChildElements()"
returns = "T"
file = "XPathBuilderBase.cs"

[[methods]]
parent = "XPathBuilderBase"
name = "AllComments"
sig = "T AllComments()"
returns = "T"
file = "XPathBuilderBase.cs"

[[methods]]
parent = "XPathBuilderBase"
name = "AllDescedentElements"
sig = "T AllDescedentElements()"
returns = "T"
file = "XPathBuilderBase.cs"

[[methods]]
parent = "XPathBuilderBase"
name = "Attributes"
sig = "T Attributes(string attributeName)"
returns = "T"
file = "XPathBuilderBase.cs"

[[methods]]
parent = "XPathBuilderBase"
name = "Elements"
sig = "T Elements(string element)"
returns = "T"
file = "XPathBuilderBase.cs"

[[methods]]
parent = "XPathBuilderBase"
name = "ElementsAtLeastAnyAttribute"
sig = "T ElementsAtLeastAnyAttribute(string element)"
returns = "T"
file = "XPathBuilderBase.cs"

[[methods]]
parent = "XPathBuilderBase"
name = "ElementsDescend"
sig = "T ElementsDescend(string element)"
returns = "T"
file = "XPathBuilderBase.cs"

[[methods]]
parent = "XPathBuilderBase"
name = "First"
sig = "T First()"
returns = "T"
file = "XPathBuilderBase.cs"

[[methods]]
parent = "XPathBuilderBase"
name = "First"
sig = "T First(int number)"
returns = "T"
file = "XPathBuilderBase.cs"

[[methods]]
parent = "XPathBuilderBase"
name = "Index"
sig = "T Index(int index)"
returns = "T"
file = "XPathBuilderBase.cs"

[[methods]]
parent = "XPathBuilderBase"
name = "InnerText"
sig = "T InnerText()"
returns = "T"
file = "XPathBuilderBase.cs"

[[methods]]
parent = "XPathBuilderBase"
name = "Or"
sig = "T Or()"
returns = "T"
file = "XPathBuilderBase.cs"

[[methods]]
parent = "XPathBuilderBase"
name = "Parent"
sig = "T Parent()"
returns = "T"
file = "XPathBuilderBase.cs"

[[methods]]
parent = "XPathBuilderBase"
name = "WhereAttributeEquals"
sig = "T WhereAttributeEquals(string attributeName, string attributeValue)"
returns = "T"
file = "XPathBuilderBase.cs"

[[methods]]
parent = "XPathBuilderBase"
name = "WhereClass"
sig = "T WhereClass(string className)"
returns = "T"
file = "XPathBuilderBase.cs"

[[methods]]
parent = "XPathBuilderBase"
name = "WhereId"
sig = "T WhereId(string id)"
returns = "T"
file = "XPathBuilderBase.cs"

[[methods]]
parent = "XPathBuilderBase"
name = "WhereIndex"
sig = "T WhereIndex(int number)"
returns = "T"
file = "XPathBuilderBase.cs"

[[methods]]
parent = "XPathBuilderBase"
name = "WhereInnerTextEquals"
sig = "T WhereInnerTextEquals(string value)"
returns = "T"
file = "XPathBuilderBase.cs"

[[methods]]
parent = "XPathBuilderBase"
name = "WhereInnerTextContains"
sig = "T WhereInnerTextContains(string value)"
returns = "T"
file = "XPathBuilderBase.cs"

[[methods]]
parent = "XPathBuilderBase"
name = "WhereLast"
sig = "T WhereLast()"
returns = "T"
file = "XPathBuilderBase.cs"

[[methods]]
parent = "XPathBuilderBase"
name = "WhereLastMinus"
sig = "T WhereLastMinus(int number)"
returns = "T"
file = "XPathBuilderBase.cs"

[[methods]]
parent = "XPathBuilderBase"
name = "WhereNotInnerTextContains"
sig = "T WhereNotInnerTextContains(string value)"
returns = "T"
file = "XPathBuilderBase.cs"

[[methods]]
parent = "XPathBuilderBase"
name = "WhereClassStartWith"
sig = "T WhereClassStartWith(string attributeValue)"
returns = "T"
file = "XPathBuilderBase.cs"

[[methods]]
parent = "XPathBuilderBase"
name = "WhereStartWith"
sig = "T WhereStartWith(string attributeName, string attributeValue)"
returns = "T"
file = "XPathBuilderBase.cs"

[[methods]]
parent = "XPathBuilderBase"
name = "WhereStartWithId"
sig = "T WhereStartWithId(string attributeValue)"
returns = "T"
file = "XPathBuilderBase.cs"

[[methods]]
parent = "XPathBuilderBase"
name = "WithExpression"
sig = "T WithExpression(Func<T, T> xPath)"
returns = "T"
file = "XPathBuilderBase.cs"

[[methods]]
parent = "XPathBuilderBase"
name = "WithExpression"
sig = "T WithExpression(T xPath)"
returns = "T"
file = "XPathBuilderBase.cs"

[[methods]]
parent = "XPathBuilderBase"
name = "WithExpression"
sig = "T WithExpression(string xPath)"
returns = "T"
file = "XPathBuilderBase.cs"

[[methods]]
parent = "XPathBuilderBase"
name = "ConcatXPath"
sig = "T ConcatXPath(string xPath)"
returns = "T"
file = "XPathBuilderBase.cs"

[[classes]]
name = "XPathBuilderEx"
ns = "FEx.WebScraping"
base = "XPathBuilderBase<XPathBuilderEx>"
file = "XPathBuilderEx.cs"

[[ctors]]
parent = "XPathBuilderEx"
sig = "XPathBuilderEx()"
file = "XPathBuilderEx.cs"

[[ctors]]
parent = "XPathBuilderEx"
sig = "XPathBuilderEx(HtmlNode node)"
file = "XPathBuilderEx.cs"

[[classes]]
name = "HtmlDocumentExtensions"
ns = "FEx.WebScraping.Extensions"
file = "Extensions\\HtmlDocumentExtensions.cs"
static = true

[[extensions]]
name = "SaveToFile"
returns = "string"
sig = "string SaveToFile(this HtmlDocument doc, string path)"
file = "Extensions\\HtmlDocumentExtensions.cs"

[[extensions]]
name = "SaveToFile"
returns = "string"
sig = "string SaveToFile(this HtmlDocument doc)"
file = "Extensions\\HtmlDocumentExtensions.cs"

[[classes]]
name = "HtmlNodeExtensions"
ns = "FEx.WebScraping.Extensions"
file = "Extensions\\HtmlNodeExtensions.cs"
static = true

[[extensions]]
name = "GetNodeAttributeStringValue"
returns = "string"
sig = "string GetNodeAttributeStringValue(this HtmlNode value, string name, string def)"
summary = "Helper method to get the value of an attribute of this node. If the attribute is not found, the default value will be returned."
file = "Extensions\\HtmlNodeExtensions.cs"

[[extensions]]
name = "GetNodeAttributeStringValue"
returns = "string"
sig = "string GetNodeAttributeStringValue(this HtmlNode value, string name)"
file = "Extensions\\HtmlNodeExtensions.cs"

[[extensions]]
name = "GetNodeAttributeBoolValue"
returns = "bool"
sig = "bool GetNodeAttributeBoolValue(this HtmlNode value, string name, bool def)"
file = "Extensions\\HtmlNodeExtensions.cs"

[[extensions]]
name = "GetNodeAttributeBoolValue"
returns = "bool"
sig = "bool GetNodeAttributeBoolValue(this HtmlNode value, string name)"
file = "Extensions\\HtmlNodeExtensions.cs"

[[extensions]]
name = "GetNodeAttributeIntValue"
returns = "int"
sig = "int GetNodeAttributeIntValue(this HtmlNode value, string name, int def)"
file = "Extensions\\HtmlNodeExtensions.cs"

[[extensions]]
name = "GetNodeAttributeIntValue"
returns = "int"
sig = "int GetNodeAttributeIntValue(this HtmlNode value, string name)"
file = "Extensions\\HtmlNodeExtensions.cs"

[[extensions]]
name = "GetSrc"
returns = "string"
sig = "string GetSrc(this HtmlNode value)"
file = "Extensions\\HtmlNodeExtensions.cs"

[[extensions]]
name = "GetHref"
returns = "string"
sig = "string GetHref(this HtmlNode value)"
file = "Extensions\\HtmlNodeExtensions.cs"

[[extensions]]
name = "GetNodeTypeAttributeValue"
returns = "string"
sig = "string GetNodeTypeAttributeValue(this HtmlNode value)"
file = "Extensions\\HtmlNodeExtensions.cs"

[[extensions]]
name = "IsNodeLinkElementOfType"
returns = "bool"
sig = "bool IsNodeLinkElementOfType(this HtmlNode value, string type)"
file = "Extensions\\HtmlNodeExtensions.cs"

[[extensions]]
name = "IsInBody"
returns = "bool"
sig = "bool IsInBody(this HtmlNode value)"
file = "Extensions\\HtmlNodeExtensions.cs"

[[extensions]]
name = "SelectSingleNode"
returns = "HtmlNode"
sig = "HtmlNode SelectSingleNode(this HtmlNode value, Func<XPathBuilderEx, XPathBuilderEx> xpath)"
summary = "Selects the first XmlNode that matches the XPath expression."
file = "Extensions\\HtmlNodeExtensions.cs"

[[extensions]]
name = "SelectNodes"
returns = "HtmlNodeCollection"
sig = "HtmlNodeCollection SelectNodes(this HtmlNode value, Func<XPathBuilderEx, XPathBuilderEx> xpath)"
summary = "Selects a list of nodes matching the expression."
file = "Extensions\\HtmlNodeExtensions.cs"

[[classes]]
name = "WebBrowserScraperExtensions"
ns = "FEx.WebScraping.Extensions"
file = "Extensions\\WebBrowserScraperExtensions.cs"
static = true

[[extensions]]
name = "LoadHtmlDocumentAsync"
returns = "Task<HtmlDocument>"
sig = "Task<HtmlDocument> LoadHtmlDocumentAsync(this IWebBrowserScraper scraper, Uri pageLink)"
file = "Extensions\\WebBrowserScraperExtensions.cs"

[[extensions]]
name = "LoadHtmlDocumentAsync"
returns = "Task<HtmlDocument>"
sig = "Task<HtmlDocument> LoadHtmlDocumentAsync(this IWebBrowserScraper scraper, Uri pageLink, Action<HtmlWeb> configWeb)"
file = "Extensions\\WebBrowserScraperExtensions.cs"

[[extensions]]
name = "LoadAsync"
returns = "Task"
sig = "Task LoadAsync(this IWebBrowserScraper scraper, Uri pageLink, Action<Uri, HtmlWeb, HtmlDocument> action)"
file = "Extensions\\WebBrowserScraperExtensions.cs"

[[extensions]]
name = "LoadAsync"
returns = "Task"
sig = "Task LoadAsync(this IWebBrowserScraper scraper, Uri pageLink, Action<Uri, HtmlWeb, HtmlDocument> action, Action<HtmlWeb> configWeb)"
file = "Extensions\\WebBrowserScraperExtensions.cs"

[[extensions]]
name = "LoadAsync"
returns = "Task<T>"
sig = "Task<T> LoadAsync<T>(this IWebBrowserScraper scraper, Uri pageLink, Func<Uri, HtmlWeb, HtmlDocument, T> action)"
file = "Extensions\\WebBrowserScraperExtensions.cs"

[[extensions]]
name = "LoadAsync"
returns = "Task<T>"
sig = "Task<T> LoadAsync<T>(this IWebBrowserScraper scraper, Uri pageLink, Func<Uri, HtmlWeb, HtmlDocument, T> action, Action<HtmlWeb> configWeb)"
file = "Extensions\\WebBrowserScraperExtensions.cs"

[[extensions]]
name = "Load"
returns = "T"
sig = "T Load<T>(this IWebBrowserScraper scraper, Uri pageLink, Func<Uri, HtmlWeb, HtmlDocument, T> action)"
file = "Extensions\\WebBrowserScraperExtensions.cs"

[[extensions]]
name = "Load"
returns = "T"
sig = "T Load<T>(this IWebBrowserScraper scraper, Uri pageLink, Func<Uri, HtmlWeb, HtmlDocument, T> action, Action<HtmlWeb> configWeb)"
file = "Extensions\\WebBrowserScraperExtensions.cs"

[[extensions]]
name = "Load"
returns = "(HtmlWeb web, HtmlDocument doc)"
sig = "(HtmlWeb web, HtmlDocument doc) Load(this IWebBrowserScraper scraper, Uri pageLink)"
file = "Extensions\\WebBrowserScraperExtensions.cs"

[[extensions]]
name = "Load"
returns = "(HtmlWeb web, HtmlDocument doc)"
sig = "(HtmlWeb web, HtmlDocument doc) Load(this IWebBrowserScraper scraper, Uri pageLink, Action<HtmlWeb> configWeb)"
file = "Extensions\\WebBrowserScraperExtensions.cs"

[[classes]]
name = "WebScraperExtensions"
ns = "FEx.WebScraping.Extensions"
file = "Extensions\\WebScraperExtensions.cs"
static = true

[[extensions]]
name = "LoadHtmlDocumentAsync"
returns = "Task<HtmlDocument>"
sig = "Task<HtmlDocument> LoadHtmlDocumentAsync(this IWebScraper scraper, Uri pageLink)"
file = "Extensions\\WebScraperExtensions.cs"

[[extensions]]
name = "LoadHtmlDocumentAsync"
returns = "Task<HtmlDocument>"
sig = "Task<HtmlDocument> LoadHtmlDocumentAsync(this IWebScraper scraper, Uri pageLink, Action<HtmlWeb> configWeb)"
file = "Extensions\\WebScraperExtensions.cs"

[[extensions]]
name = "LoadHtmlDocumentAsync"
returns = "Task<HtmlDocument>"
sig = "Task<HtmlDocument> LoadHtmlDocumentAsync(this IWebScraper scraper, Uri pageLink, Action<HtmlWeb> configWeb, Encoding encoding)"
file = "Extensions\\WebScraperExtensions.cs"

[[extensions]]
name = "LoadHtmlDocumentAsync"
returns = "Task<HtmlDocument>"
sig = "Task<HtmlDocument> LoadHtmlDocumentAsync(this IWebScraper scraper, Uri pageLink, Action<HtmlWeb> configWeb, Encoding encoding, NetworkCredential credential)"
file = "Extensions\\WebScraperExtensions.cs"

[[extensions]]
name = "LoadAsync"
returns = "Task<T>"
sig = "Task<T> LoadAsync<T>(this IWebScraper scraper, Uri pageLink, Func<Uri, HtmlWeb, HtmlDocument, T> action)"
file = "Extensions\\WebScraperExtensions.cs"

[[extensions]]
name = "LoadAsync"
returns = "Task<T>"
sig = "Task<T> LoadAsync<T>(this IWebScraper scraper, Uri pageLink, Func<Uri, HtmlWeb, HtmlDocument, T> action, Action<HtmlWeb> configWeb)"
file = "Extensions\\WebScraperExtensions.cs"

[[extensions]]
name = "LoadAsync"
returns = "Task<T>"
sig = "Task<T> LoadAsync<T>(this IWebScraper scraper, Uri pageLink, Func<Uri, HtmlWeb, HtmlDocument, T> action, Action<HtmlWeb> configWeb, Encoding encoding)"
file = "Extensions\\WebScraperExtensions.cs"

[[extensions]]
name = "LoadAsync"
returns = "Task<T>"
sig = "Task<T> LoadAsync<T>(this IWebScraper scraper, Uri pageLink, Func<Uri, HtmlWeb, HtmlDocument, T> action, Action<HtmlWeb> configWeb, Encoding encoding, NetworkCredential credential)"
file = "Extensions\\WebScraperExtensions.cs"

[[extensions]]
name = "LoadHtmlDocumentAsync"
returns = "Task<HtmlDocument>"
sig = "Task<HtmlDocument> LoadHtmlDocumentAsync(this IWebScraper scraper, HtmlWeb web, Uri pageLink)"
file = "Extensions\\WebScraperExtensions.cs"

[[extensions]]
name = "LoadHtmlDocumentAsync"
returns = "Task<HtmlDocument>"
sig = "Task<HtmlDocument> LoadHtmlDocumentAsync(this IWebScraper scraper, HtmlWeb web, Uri pageLink, Encoding encoding)"
file = "Extensions\\WebScraperExtensions.cs"

[[extensions]]
name = "LoadHtmlDocumentAsync"
returns = "Task<HtmlDocument>"
sig = "Task<HtmlDocument> LoadHtmlDocumentAsync(this IWebScraper scraper, HtmlWeb web, Uri pageLink, Encoding encoding, NetworkCredential credential)"
file = "Extensions\\WebScraperExtensions.cs"

[[extensions]]
name = "Load"
returns = "(HtmlWeb web, Task<HtmlDocument> docTask)"
sig = "(HtmlWeb web, Task<HtmlDocument> docTask) Load(this IWebScraper scraper, Uri pageLink)"
file = "Extensions\\WebScraperExtensions.cs"

[[extensions]]
name = "Load"
returns = "(HtmlWeb web, Task<HtmlDocument> docTask)"
sig = "(HtmlWeb web, Task<HtmlDocument> docTask) Load(this IWebScraper scraper, Uri pageLink, Action<HtmlWeb> configWeb)"
file = "Extensions\\WebScraperExtensions.cs"

[[extensions]]
name = "Load"
returns = "(HtmlWeb web, Task<HtmlDocument> docTask)"
sig = "(HtmlWeb web, Task<HtmlDocument> docTask) Load(this IWebScraper scraper, Uri pageLink, Action<HtmlWeb> configWeb, Encoding encoding)"
file = "Extensions\\WebScraperExtensions.cs"

[[extensions]]
name = "Load"
returns = "(HtmlWeb web, Task<HtmlDocument> docTask)"
sig = "(HtmlWeb web, Task<HtmlDocument> docTask) Load(this IWebScraper scraper, Uri pageLink, Action<HtmlWeb> configWeb, Encoding encoding, NetworkCredential credential)"
file = "Extensions\\WebScraperExtensions.cs"

[[interfaces]]
name = "IWebBrowserScraper"
ns = "FEx.WebScraping.Abstractions.Interfaces"
file = "Abstractions\\Interfaces\\IWebBrowserScraper.cs"

[[methods]]
parent = "IWebBrowserScraper"
name = "LoadHtmlDocumentAsync"
sig = "Task<HtmlDocument> LoadHtmlDocumentAsync(Uri pageLink, Action<HtmlWeb> configWeb, Func<string, bool> isBrowserScriptCompleted)"
returns = "Task<HtmlDocument>"
file = "Abstractions\\Interfaces\\IWebBrowserScraper.cs"

[[methods]]
parent = "IWebBrowserScraper"
name = "LoadAsync"
sig = "Task LoadAsync(Uri pageLink, Action<Uri, HtmlWeb, HtmlDocument> action, Action<HtmlWeb> configWeb, Func<string, bool> isBrowserScriptCompleted)"
returns = "Task"
file = "Abstractions\\Interfaces\\IWebBrowserScraper.cs"

[[methods]]
parent = "IWebBrowserScraper"
name = "LoadAsync"
sig = "Task<T> LoadAsync<T>(Uri pageLink, Func<Uri, HtmlWeb, HtmlDocument, T> action, Action<HtmlWeb> configWeb, Func<string, bool> isBrowserScriptCompleted)"
returns = "Task<T>"
file = "Abstractions\\Interfaces\\IWebBrowserScraper.cs"

[[methods]]
parent = "IWebBrowserScraper"
name = "Load"
sig = "T Load<T>(Uri pageLink, Func<Uri, HtmlWeb, HtmlDocument, T> action, Action<HtmlWeb> configWeb, Func<string, bool> isBrowserScriptCompleted)"
returns = "T"
file = "Abstractions\\Interfaces\\IWebBrowserScraper.cs"

[[methods]]
parent = "IWebBrowserScraper"
name = "Load"
sig = "(HtmlWeb web, HtmlDocument doc) Load(Uri pageLink, Action<HtmlWeb> configWeb, Func<string, bool> isBrowserScriptCompleted)"
returns = "(HtmlWeb web, HtmlDocument doc)"
file = "Abstractions\\Interfaces\\IWebBrowserScraper.cs"

[[interfaces]]
name = "IWebScraper"
ns = "FEx.WebScraping.Abstractions.Interfaces"
file = "Abstractions\\Interfaces\\IWebScraper.cs"

[[methods]]
parent = "IWebScraper"
name = "LoadHtmlDocumentAsync"
sig = "Task<HtmlDocument> LoadHtmlDocumentAsync(Uri pageLink, Action<HtmlWeb> configWeb, Encoding encoding, NetworkCredential credential, CancellationToken cancellationToken)"
returns = "Task<HtmlDocument>"
file = "Abstractions\\Interfaces\\IWebScraper.cs"

[[methods]]
parent = "IWebScraper"
name = "LoadAsync"
sig = "Task<T> LoadAsync<T>(Uri pageLink, Func<Uri, HtmlWeb, HtmlDocument, T> action, Action<HtmlWeb> configWeb, Encoding encoding, NetworkCredential credential, CancellationToken cancellationToken)"
returns = "Task<T>"
file = "Abstractions\\Interfaces\\IWebScraper.cs"

[[methods]]
parent = "IWebScraper"
name = "LoadHtmlDocumentAsync"
sig = "Task<HtmlDocument> LoadHtmlDocumentAsync(HtmlWeb web, Uri pageLink, Encoding encoding, NetworkCredential credential, CancellationToken cancellationToken)"
returns = "Task<HtmlDocument>"
file = "Abstractions\\Interfaces\\IWebScraper.cs"

[[methods]]
parent = "IWebScraper"
name = "Load"
sig = "(HtmlWeb web, Task<HtmlDocument> docTask) Load(Uri pageLink, Action<HtmlWeb> configWeb, Encoding encoding, NetworkCredential credential, CancellationToken cancellationToken)"
returns = "(HtmlWeb web, Task<HtmlDocument> docTask)"
file = "Abstractions\\Interfaces\\IWebScraper.cs"

