<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFrameworkId)</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Arcus.Security.Providers.AzureKeyVault" Version="2.0.0" />
		<PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.4.0" />
		<PackageReference Include="Azure.Identity" Version="1.17.0" />
		<PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="$(DotNetNugetsVersion)" />
		<PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="$(DotNetNugetsVersion)" />
		<PackageReference Include="Polly" Version="8.6.4" />
		<PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
	</ItemGroup>

</Project>
