<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(StandardTargetFrameworkIds)</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="StrongInject.Extensions.DependencyInjection" Version="1.4.4" />
	</ItemGroup>

	<ItemGroup Condition="$(DefineConstants.Contains('NETSTANDARD'))">
		<PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FEx.DI.Abstractions\FEx.DI.Abstractions.csproj" />
		<ProjectReference Include="..\FEx.Extensions\FEx.Extensions.csproj" />
	</ItemGroup>

</Project>
