<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(StandardTargetFrameworkIds)</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\FEx.Encryption\FEx.Encryption.csproj" />
		<ProjectReference Include="..\FEx.Json\FEx.Json.csproj" />
		<ProjectReference Include="..\FEx.Utilities\FEx.Utilities.csproj" />
	</ItemGroup>

</Project>
