<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(StandardTargetFrameworkIds)</TargetFrameworks>
		<Description>Secure storage service for persisting sensitive data</Description>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\FEx.Encryption\FEx.Encryption.csproj" />
	  <ProjectReference Include="..\FEx.Json\FEx.Json.csproj" />
	</ItemGroup>

</Project>
