<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFrameworkId)</TargetFramework>
		<UseMaui>true</UseMaui>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Update="Microsoft.Maui.Controls" Version="8.0.70" />
		<PackageReference Update="Microsoft.Maui.Controls.Compatibility" Version="8.0.70" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\FEx.Abstractions\FEx.Abstractions.csproj" />
	  <ProjectReference Include="..\FEx.Asyncx\FEx.Asyncx.csproj" />
	</ItemGroup>

</Project>
