<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(StandardTargetFrameworkIds)</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MimeMapping" Version="3.0.1" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\FEx.Extensions\FEx.Extensions.csproj" />
	  <ProjectReference Include="..\FEx.Json\FEx.Json.csproj" />
	  <ProjectReference Include="..\FEx.Platforms.Abstractions\FEx.Platforms.Abstractions.csproj" />
	</ItemGroup>

</Project>
