<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(TargetFrameworkIds)</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MimeMapping" Version="2.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FEx.Json\FEx.Json.csproj" />
		<ProjectReference Include="..\FEx.Utilities\FEx.Utilities.csproj" />
	</ItemGroup>

</Project>
