<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFrameworkId)</TargetFramework>
		<IsTestProject>true</IsTestProject>
		<UseMaui>true</UseMaui>
		<SkipValidateMauiImplicitPackageReferences>true</SkipValidateMauiImplicitPackageReferences>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\FEx.Maui\FEx.Maui.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Update="Microsoft.Maui.Controls" Version="10.0.71" />
		<PackageReference Update="Microsoft.Maui.Controls.Compatibility" Version="10.0.71" />
	</ItemGroup>

</Project>
