<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(StandardTargetFrameworkIds)</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\DependencyInjection.Abstractions\FEx.DependencyInjection.Abstractions.csproj"/>
		<ProjectReference Include="..\Core.Abstractions\FEx.Core.Abstractions.csproj"/>
		<ProjectReference Include="..\Logging.Abstractions\FEx.Logging.Abstractions.csproj"/>
	</ItemGroup>

</Project>
