<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(StandardTargetFrameworkIds)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Reactive.Linq" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup Condition="$(DefineConstants.Contains('NETSTANDARD'))">
    <PackageReference Include="System.Reflection.Emit.Lightweight" Version="4.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FEx.Abstractions\FEx.Abstractions.csproj" />
    <ProjectReference Include="..\FEx.Extensions\FEx.Extensions.csproj" />
    <ProjectReference Include="..\FEx.Fundamentals\FEx.Fundamentals.csproj" />
    <ProjectReference Include="..\FEx.Rx\FEx.Rx.csproj" />
  </ItemGroup>

</Project>
