<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(StandardTargetFrameworkIds)</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ReactiveUI.Avalonia" Version="11.3.8" />
		<PackageReference Include="MessageBox.Avalonia" Version="3.2.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Common.Abstractions\FEx.Common.Abstractions.csproj" />
		<ProjectReference Include="..\Common\FEx.Common.csproj" />
		<ProjectReference Include="..\DependencyInjection\FEx.DependencyInjection.csproj" />
		<ProjectReference Include="..\FEx.Asyncx\FEx.Asyncx.csproj" />
		<ProjectReference Include="..\FEx.Json\FEx.Json.csproj" />
		<ProjectReference Include="..\FEx.MVVM\FEx.MVVM.csproj" />
		<ProjectReference Include="..\FEx.Platforms\FEx.Platforms.csproj" />
	</ItemGroup>

</Project>
