<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(StandardTargetFrameworkIds)</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="HtmlAgilityPack" Version="1.11.59" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\FEx.Asyncx\FEx.Asyncx.csproj" />
	</ItemGroup>

</Project>
