<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFrameworkId)</TargetFramework>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Agnostics\FEx.Agnostics.csproj" />
		<ProjectReference Include="..\..\src\Agnostics.Abstractions\FEx.Agnostics.Abstractions.csproj" />
		<ProjectReference Include="..\..\src\Core.Abstractions\FEx.Core.Abstractions.csproj" />
		<ProjectReference Include="..\..\src\FEx.Encryption\FEx.Encryption.csproj" />
		<ProjectReference Include="..\..\src\FEx.Json\FEx.Json.csproj" />
	</ItemGroup>

</Project>
