<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(StandardTargetFrameworkIds)</TargetFrameworks>
        <Description>Abstractions (interfaces and options) for OneDrive client via Microsoft Graph API</Description>
    </PropertyGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
        <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="$(DotNetNugetsVersion)" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Graph" Version="5.103.0" />
        <PackageReference Include="Microsoft.Kiota.Abstractions" Version="1.22.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Agnostics.Abstractions\FEx.Agnostics.Abstractions.csproj" />
    </ItemGroup>

</Project>
