<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(StandardTargetFrameworkIds)</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Identity" Version="1.13.2" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="$(EFCoreVersion)" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="$(EFCoreVersion)" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="$(EFCoreVersion)" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="$(EFCoreVersion)">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="$(DotNetNugetsVersion)" />
		<PackageReference Include="System.Drawing.Common" Version="$(DotNetNugetsVersion)" />
		<PackageReference Include="System.Formats.Asn1" Version="$(DotNetNugetsVersion)" />
		<PackageReference Include="System.Text.Json" Version="$(DotNetNugetsVersion)" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FEx.Abstractions\FEx.Abstractions.csproj" />
		<ProjectReference Include="..\FEx.Basics\FEx.Basics.csproj" />
		<ProjectReference Include="..\FEx.Extensions\FEx.Extensions.csproj" />
		<ProjectReference Include="..\FEx.Json\FEx.Json.csproj" />
		<ProjectReference Include="..\FEx.Logging\FEx.Logging.csproj" />
	</ItemGroup>

</Project>
