<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <Configurations>Debug;Release;Build</Configurations>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Nuke.Common" Version="10.1.0" />
        <PackageReference Include="Nuke.Utilities" Version="10.1.0" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.VisualStudio.Threading" Version="17.14.15" />
    </ItemGroup>

</Project>
