<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(StandardTargetFrameworkIds)</TargetFrameworks>
		<Description>Async and parallel programming related FEx utilities</Description>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.VisualStudio.Threading" Version="17.12.19" />
		<PackageReference Include="Microsoft.VisualStudio.Validation" Version="17.8.8" />
		<PackageReference Include="StrongInject" Version="1.4.4" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\FEx.Basics\FEx.Basics.csproj" />
	  <ProjectReference Include="..\FEx.Extensions\FEx.Extensions.csproj" />
	  <ProjectReference Include="..\FEx.Logging.Abstractions\FEx.Logging.Abstractions.csproj" />
	</ItemGroup>

</Project>
