<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(TargetFrameworkIds)</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.VisualStudio.Threading" Version="17.7.30" />
		<PackageReference Include="Microsoft.VisualStudio.Validation" Version="17.6.11" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FEx.Extensions\FEx.Extensions.csproj" />
		<ProjectReference Include="..\FEx.Fundamentals\FEx.Fundamentals.csproj" />
	</ItemGroup>

</Project>
