<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>$(StandardTargetFrameworkIds)</TargetFrameworks>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Azure.Identity" Version="1.17.0" />
		<PackageReference Include="Rollbar.OfflinePersistence" Version="5.2.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="$(EFCoreVersion)" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="$(EFCoreVersion)" />
		<PackageReference Include="System.Drawing.Common" Version="$(DotNetNugetsVersion)" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Core\FEx.Core.csproj" />
		<ProjectReference Include="..\FEx.Asyncx\FEx.Asyncx.csproj" />
		<ProjectReference Include="..\Logging\FEx.Logging.csproj" />
		<ProjectReference Include="..\FEx.Platforms\FEx.Platforms.csproj" />
		<ProjectReference Include="..\FEx.Telemetry\FEx.Telemetry.csproj" />
	</ItemGroup>
</Project>

