<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFrameworkId)</TargetFramework>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\PersistentStorage/FEx.PersistentStorage.csproj" />
		<ProjectReference Include="..\..\src\PersistentStorage.Rx\FEx.PersistentStorage.Rx.csproj" />
	</ItemGroup>

</Project>
