<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFrameworkId)</TargetFramework>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\src\FEx.MVVM\FEx.MVVM.csproj" />
	  <ProjectReference Include="..\..\src\FEx.MVVM.Rx\FEx.MVVM.Rx.csproj" />
	  <ProjectReference Include="..\..\src\FEx.MVVM.Rx.Legacy\FEx.MVVM.Rx.Legacy.csproj" />
	</ItemGroup>

</Project>
