<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(TargetFrameworkIds)</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommandLineParser" Version="2.9.1" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\FEx.Extensions\FEx.Extensions.csproj" />
	</ItemGroup>

</Project>