<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(StandardTargetFrameworkIds)</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="StrongInject.Extensions.DependencyInjection" Version="1.4.4" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\FEx.FileSystem\FEx.FileSystem.csproj" />
	  <ProjectReference Include="..\FEx.MVVM\FEx.MVVM.csproj" />
	  <ProjectReference Include="..\FEx.Webx\FEx.Webx.csproj" />
	</ItemGroup>

</Project>
