<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(StandardTargetFrameworkIds)</TargetFrameworks>
		<Description>Cross-framework file system utilities for directory walking, safe deletion, and compression</Description>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Agnostics\FEx.Agnostics.csproj" />
	  <ProjectReference Include="..\Core\FEx.Core.csproj" />
	  <ProjectReference Include="..\FEx.Asyncx\FEx.Asyncx.csproj" />
	</ItemGroup>

</Project>
