<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(StandardTargetFrameworkIds)</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ReactiveUI" Version="20.1.1" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\FEx.DependencyInjection\FEx.DependencyInjection.csproj" />
	  <ProjectReference Include="..\FEx.MVVM.Abstractions\FEx.MVVM.Abstractions.csproj" />
	</ItemGroup>

</Project>
